CREATE SCHEMA "app";
--> statement-breakpoint
CREATE SCHEMA "auth";
--> statement-breakpoint
CREATE SEQUENCE "app"."factory_version_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "app"."native_entity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 4000000000000000 CACHE 1;--> statement-breakpoint
CREATE TABLE "auth"."account" (
	"id" text PRIMARY KEY NOT NULL,
	"accountId" text NOT NULL,
	"providerId" text NOT NULL,
	"userId" text NOT NULL,
	"accessToken" text,
	"refreshToken" text,
	"idToken" text,
	"accessTokenExpiresAt" timestamp with time zone,
	"refreshTokenExpiresAt" timestamp with time zone,
	"scope" text,
	"password" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "account_provider_identity_unique" UNIQUE("accountId","providerId")
);
--> statement-breakpoint
CREATE TABLE "app"."agent_runs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."agent_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"kind" text NOT NULL,
	"plan_id" bigint,
	"feature_id" bigint,
	"fix_attempt_id" bigint,
	"automation_run_id" bigint,
	"log_key" text NOT NULL,
	"success" smallint NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "agent_runs_kind_check" CHECK (kind = ANY (ARRAY['plan_analyze'::text, 'plan_refine'::text, 'generate'::text, 'verify'::text, 'fix'::text, 'automation'::text, 'chat'::text, 'resolve_conflict'::text])),
	CONSTRAINT "agent_runs_success_check" CHECK (success = ANY (ARRAY[0, 1])),
	CONSTRAINT "agent_runs_owner" CHECK (num_nonnulls(plan_id, feature_id, fix_attempt_id, automation_run_id) >= 1)
);
--> statement-breakpoint
CREATE TABLE "app"."agents" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."agents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"installation_id" bigint NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"instructions" text NOT NULL,
	"model" text DEFAULT 'cloudflare/anthropic/claude-sonnet-5' NOT NULL,
	"is_builtin" smallint DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "agents_id_installation_unique" UNIQUE("id","installation_id"),
	CONSTRAINT "agents_installation_slug_unique" UNIQUE("installation_id","slug"),
	CONSTRAINT "agents_is_builtin_check" CHECK (is_builtin = ANY (ARRAY[0, 1])),
	CONSTRAINT "agents_slug_format" CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text)
);
--> statement-breakpoint
CREATE TABLE "app"."automation_runs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."automation_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"automation_id" bigint NOT NULL,
	"status" text DEFAULT 'running' NOT NULL,
	"pr_number" integer,
	"commit_sha" text,
	"error" text,
	"input_tokens" bigint DEFAULT 0 NOT NULL,
	"output_tokens" bigint DEFAULT 0 NOT NULL,
	"cache_read_tokens" bigint DEFAULT 0 NOT NULL,
	"cache_write_tokens" bigint DEFAULT 0 NOT NULL,
	"cost_usd" numeric(20, 10) DEFAULT 0 NOT NULL,
	"model" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "automation_runs_status_check" CHECK (status = ANY (ARRAY['running'::text, 'pr_opened'::text, 'no_changes'::text, 'checks_failed'::text, 'failed'::text])),
	CONSTRAINT "automation_runs_pr_number_check" CHECK ((pr_number IS NULL) OR (pr_number > 0)),
	CONSTRAINT "automation_runs_input_tokens_check" CHECK (input_tokens >= 0),
	CONSTRAINT "automation_runs_output_tokens_check" CHECK (output_tokens >= 0),
	CONSTRAINT "automation_runs_cache_read_tokens_check" CHECK (cache_read_tokens >= 0),
	CONSTRAINT "automation_runs_cache_write_tokens_check" CHECK (cache_write_tokens >= 0),
	CONSTRAINT "automation_runs_cost_usd_check" CHECK (cost_usd >= (0)::numeric)
);
--> statement-breakpoint
CREATE TABLE "app"."automations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."automations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"repository_id" bigint NOT NULL,
	"name" text NOT NULL,
	"prompt" text NOT NULL,
	"schedule_kind" text NOT NULL,
	"time_of_day" time,
	"day_of_week" smallint,
	"enabled" smallint DEFAULT 1 NOT NULL,
	"next_run_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "automations_schedule_kind_check" CHECK (schedule_kind = ANY (ARRAY['hourly'::text, 'daily'::text, 'weekly'::text])),
	CONSTRAINT "automations_day_of_week_check" CHECK ((day_of_week >= 0) AND (day_of_week <= 6)),
	CONSTRAINT "automations_enabled_check" CHECK (enabled = ANY (ARRAY[0, 1])),
	CONSTRAINT "automations_schedule_shape" CHECK (((schedule_kind = 'hourly'::text) AND (time_of_day IS NULL) AND (day_of_week IS NULL)) OR ((schedule_kind = 'daily'::text) AND (time_of_day IS NOT NULL) AND (day_of_week IS NULL)) OR ((schedule_kind = 'weekly'::text) AND (time_of_day IS NOT NULL) AND (day_of_week IS NOT NULL)))
);
--> statement-breakpoint
CREATE TABLE "app"."change_request_counters" (
	"repository_id" bigint PRIMARY KEY NOT NULL,
	"last_number" integer NOT NULL,
	CONSTRAINT "change_request_counters_last_number_check" CHECK (last_number > 0)
);
--> statement-breakpoint
CREATE TABLE "app"."change_requests" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."change_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"repository_id" bigint NOT NULL,
	"number" integer NOT NULL,
	"feature_id" bigint,
	"title" text NOT NULL,
	"source_branch" text NOT NULL,
	"target_branch" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"source_head" text,
	"target_head" text,
	"merge_base" text,
	"mergeable" smallint,
	"conflict_files" jsonb,
	"files" jsonb,
	"diff_key" text,
	"patch_truncated" smallint DEFAULT 0 NOT NULL,
	"review_status" text,
	"merged_head" text,
	"opened_by" text DEFAULT 'factory' NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "change_requests_repo_number_unique" UNIQUE("repository_id","number"),
	CONSTRAINT "change_requests_number_check" CHECK (number > 0),
	CONSTRAINT "change_requests_status_check" CHECK (status = ANY (ARRAY['open'::text, 'merged'::text, 'closed'::text])),
	CONSTRAINT "change_requests_mergeable_check" CHECK (mergeable = ANY (ARRAY[0, 1])),
	CONSTRAINT "change_requests_patch_truncated_check" CHECK (patch_truncated = ANY (ARRAY[0, 1])),
	CONSTRAINT "change_requests_review_status_check" CHECK ((review_status IS NULL) OR (review_status = ANY (ARRAY['approved'::text, 'changes_requested'::text])))
);
--> statement-breakpoint
CREATE TABLE "app"."chat_messages" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."chat_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"feature_id" bigint NOT NULL,
	"role" text NOT NULL,
	"body" text NOT NULL,
	"author" text,
	"author_id" bigint,
	"status" text DEFAULT 'done' NOT NULL,
	"outcome" text,
	"commit_sha" text,
	"error" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "chat_messages_role_check" CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text])),
	CONSTRAINT "chat_messages_status_check" CHECK (status = ANY (ARRAY['queued'::text, 'running'::text, 'done'::text, 'failed'::text])),
	CONSTRAINT "chat_messages_outcome_check" CHECK ((outcome IS NULL) OR (outcome = ANY (ARRAY['changed'::text, 'no_changes'::text, 'tests_failed'::text])))
);
--> statement-breakpoint
CREATE TABLE "app"."cockpit_comments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."cockpit_comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"feature_id" bigint NOT NULL,
	"path" text NOT NULL,
	"line" integer NOT NULL,
	"side" text DEFAULT 'additions' NOT NULL,
	"body" text NOT NULL,
	"author" text NOT NULL,
	"author_id" bigint,
	"status" text DEFAULT 'open' NOT NULL,
	"fix_attempt_id" bigint,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "cockpit_comments_line_check" CHECK (line > 0),
	CONSTRAINT "cockpit_comments_side_check" CHECK (side = ANY (ARRAY['additions'::text, 'deletions'::text])),
	CONSTRAINT "cockpit_comments_status_check" CHECK (status = ANY (ARRAY['open'::text, 'dispatched'::text]))
);
--> statement-breakpoint
CREATE TABLE "app"."connections" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."connections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"installation_id" bigint NOT NULL,
	"name" text NOT NULL,
	"kind" text DEFAULT 'mcp' NOT NULL,
	"url" text NOT NULL,
	"tool_allowlist" jsonb,
	"auth_ciphertext" text,
	"optional" smallint DEFAULT 1 NOT NULL,
	"auth_type" text DEFAULT 'none' NOT NULL,
	"auth_config_ciphertext" text,
	"oauth_token_expires_at" timestamp with time zone,
	"oauth_needs_reauth" smallint DEFAULT 0 NOT NULL,
	"oauth_has_refresh_token" smallint DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "connections_id_installation_unique" UNIQUE("id","installation_id"),
	CONSTRAINT "connections_installation_name_unique" UNIQUE("installation_id","name"),
	CONSTRAINT "connections_kind_check" CHECK (kind = ANY (ARRAY['mcp'::text, 'api'::text])),
	CONSTRAINT "connections_optional_check" CHECK (optional = ANY (ARRAY[0, 1])),
	CONSTRAINT "connections_auth_type_check" CHECK (auth_type = ANY (ARRAY['none'::text, 'bearer'::text, 'api_key'::text, 'client_credentials'::text, 'oauth'::text])),
	CONSTRAINT "connections_oauth_needs_reauth_check" CHECK (oauth_needs_reauth = ANY (ARRAY[0, 1])),
	CONSTRAINT "connections_oauth_has_refresh_token_check" CHECK (oauth_has_refresh_token = ANY (ARRAY[0, 1]))
);
--> statement-breakpoint
CREATE TABLE "app"."cr_checks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."cr_checks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"change_request_id" bigint NOT NULL,
	"name" text NOT NULL,
	"status" text NOT NULL,
	"summary" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "cr_checks_name_unique" UNIQUE("change_request_id","name"),
	CONSTRAINT "cr_checks_status_check" CHECK (status = ANY (ARRAY['running'::text, 'passed'::text, 'failed'::text, 'error'::text]))
);
--> statement-breakpoint
CREATE TABLE "app"."cr_comments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."cr_comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"change_request_id" bigint NOT NULL,
	"file" text,
	"line" integer,
	"author" text NOT NULL,
	"kind" text DEFAULT 'comment' NOT NULL,
	"severity" text,
	"body" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "cr_comments_line_check" CHECK ((line IS NULL) OR (line > 0)),
	CONSTRAINT "cr_comments_kind_check" CHECK (kind = ANY (ARRAY['comment'::text, 'finding'::text, 'summary'::text])),
	CONSTRAINT "cr_comments_severity_check" CHECK ((severity IS NULL) OR (severity = ANY (ARRAY['P1'::text, 'P2'::text, 'P3'::text]))),
	CONSTRAINT "cr_comments_location" CHECK (((file IS NULL) AND (line IS NULL)) OR (file IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "app"."features" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."features_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"repository_id" bigint NOT NULL,
	"plan_id" bigint,
	"title" text NOT NULL,
	"spec" text NOT NULL,
	"acceptance" jsonb,
	"branch" text,
	"pr_number" integer,
	"status" text DEFAULT 'queued' NOT NULL,
	"error" text,
	"author_login" text,
	"author_id" bigint,
	"coauthor_login" text,
	"coauthor_id" bigint,
	"run_started_at" timestamp with time zone,
	"tier" text,
	"input_tokens" bigint DEFAULT 0 NOT NULL,
	"output_tokens" bigint DEFAULT 0 NOT NULL,
	"cache_read_tokens" bigint DEFAULT 0 NOT NULL,
	"cache_write_tokens" bigint DEFAULT 0 NOT NULL,
	"cost_usd" numeric(20, 10) DEFAULT 0 NOT NULL,
	"model" text,
	"runner_model" text,
	"change_request_id" bigint,
	"criteria_conflict" smallint DEFAULT 0 NOT NULL,
	"acceptance_updated_at" timestamp with time zone,
	"proposed_acceptance" jsonb,
	"chat_session_id" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "features_plan_repository_unique" UNIQUE("plan_id","repository_id"),
	CONSTRAINT "features_pr_number_check" CHECK (pr_number > 0),
	CONSTRAINT "features_status_check" CHECK (status = ANY (ARRAY['queued'::text, 'generating'::text, 'pr_opened'::text, 'no_changes'::text, 'checks_failed'::text, 'failed'::text, 'merged'::text, 'pr_closed'::text, 'abandoned'::text])),
	CONSTRAINT "features_input_tokens_check" CHECK (input_tokens >= 0),
	CONSTRAINT "features_output_tokens_check" CHECK (output_tokens >= 0),
	CONSTRAINT "features_cache_read_tokens_check" CHECK (cache_read_tokens >= 0),
	CONSTRAINT "features_cache_write_tokens_check" CHECK (cache_write_tokens >= 0),
	CONSTRAINT "features_cost_usd_check" CHECK (cost_usd >= (0)::numeric),
	CONSTRAINT "features_criteria_conflict_check" CHECK (criteria_conflict = ANY (ARRAY[0, 1]))
);
--> statement-breakpoint
CREATE TABLE "app"."fix_attempts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."fix_attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"repository_id" bigint NOT NULL,
	"pr_number" integer NOT NULL,
	"trigger" text NOT NULL,
	"status" text DEFAULT 'running' NOT NULL,
	"commit_sha" text,
	"error" text,
	"input_tokens" bigint DEFAULT 0 NOT NULL,
	"output_tokens" bigint DEFAULT 0 NOT NULL,
	"cache_read_tokens" bigint DEFAULT 0 NOT NULL,
	"cache_write_tokens" bigint DEFAULT 0 NOT NULL,
	"cost_usd" numeric(20, 10) DEFAULT 0 NOT NULL,
	"model" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "fix_attempts_pr_number_check" CHECK (pr_number > 0),
	CONSTRAINT "fix_attempts_status_check" CHECK (status = ANY (ARRAY['running'::text, 'fixed'::text, 'no_changes'::text, 'tests_failed'::text, 'failed'::text])),
	CONSTRAINT "fix_attempts_input_tokens_check" CHECK (input_tokens >= 0),
	CONSTRAINT "fix_attempts_output_tokens_check" CHECK (output_tokens >= 0),
	CONSTRAINT "fix_attempts_cache_read_tokens_check" CHECK (cache_read_tokens >= 0),
	CONSTRAINT "fix_attempts_cache_write_tokens_check" CHECK (cache_write_tokens >= 0),
	CONSTRAINT "fix_attempts_cost_usd_check" CHECK (cost_usd >= (0)::numeric)
);
--> statement-breakpoint
CREATE TABLE "app"."installation_repo_sync" (
	"installation_id" bigint PRIMARY KEY NOT NULL,
	"last_synced_at" timestamp with time zone,
	"syncing_until" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "app"."installations" (
	"id" bigint PRIMARY KEY DEFAULT nextval('app.native_entity_id_seq'::regclass) NOT NULL,
	"account_login" text NOT NULL,
	"account_id" bigint NOT NULL,
	"account_type" text NOT NULL,
	"suspended" smallint DEFAULT 0 NOT NULL,
	"provider" text DEFAULT 'github' NOT NULL,
	"installer_github_id" bigint,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "installations_id_provider_unique" UNIQUE("id","provider"),
	CONSTRAINT "installations_provider_login_unique" UNIQUE("provider","account_login"),
	CONSTRAINT "installations_provider_account_unique" UNIQUE("provider","account_id"),
	CONSTRAINT "installations_account_type_check" CHECK (account_type = ANY (ARRAY['Organization'::text, 'User'::text])),
	CONSTRAINT "installations_suspended_check" CHECK (suspended = ANY (ARRAY[0, 1])),
	CONSTRAINT "installations_provider_check" CHECK (provider = ANY (ARRAY['github'::text, 'artifacts'::text]))
);
--> statement-breakpoint
CREATE TABLE "auth"."invitation" (
	"id" text PRIMARY KEY NOT NULL,
	"organizationId" text NOT NULL,
	"email" text NOT NULL,
	"role" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"inviterId" text NOT NULL,
	CONSTRAINT "invitation_role_check" CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text])),
	CONSTRAINT "invitation_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'canceled'::text]))
);
--> statement-breakpoint
CREATE TABLE "auth"."member" (
	"id" text PRIMARY KEY NOT NULL,
	"organizationId" text NOT NULL,
	"userId" text NOT NULL,
	"role" text DEFAULT 'member' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "member_organization_user_unique" UNIQUE("organizationId","userId"),
	CONSTRAINT "member_role_check" CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text]))
);
--> statement-breakpoint
CREATE TABLE "auth"."oauthAccessToken" (
	"id" text PRIMARY KEY NOT NULL,
	"accessToken" text NOT NULL,
	"refreshToken" text,
	"accessTokenExpiresAt" timestamp with time zone NOT NULL,
	"refreshTokenExpiresAt" timestamp with time zone NOT NULL,
	"clientId" text NOT NULL,
	"userId" text,
	"scopes" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "oauthAccessToken_accessToken_key" UNIQUE("accessToken"),
	CONSTRAINT "oauthAccessToken_refreshToken_key" UNIQUE("refreshToken")
);
--> statement-breakpoint
CREATE TABLE "auth"."oauthApplication" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text,
	"icon" text,
	"metadata" text,
	"clientId" text NOT NULL,
	"clientSecret" text,
	"redirectUrls" text NOT NULL,
	"type" text NOT NULL,
	"disabled" boolean DEFAULT false NOT NULL,
	"userId" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "oauthApplication_clientId_key" UNIQUE("clientId")
);
--> statement-breakpoint
CREATE TABLE "auth"."oauthConsent" (
	"id" text PRIMARY KEY NOT NULL,
	"clientId" text NOT NULL,
	"userId" text NOT NULL,
	"scopes" text NOT NULL,
	"consentGiven" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "oauth_consent_client_user_unique" UNIQUE("clientId","userId")
);
--> statement-breakpoint
CREATE TABLE "auth"."organization" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"logo" text,
	"metadata" text,
	"createdAt" timestamp with time zone NOT NULL,
	"installationId" bigint NOT NULL,
	CONSTRAINT "organization_slug_key" UNIQUE("slug"),
	CONSTRAINT "organization_installationId_key" UNIQUE("installationId")
);
--> statement-breakpoint
CREATE TABLE "app"."plan_repositories" (
	"plan_id" bigint NOT NULL,
	"repository_id" bigint NOT NULL,
	"position" smallint NOT NULL,
	CONSTRAINT "plan_repositories_pkey" PRIMARY KEY("plan_id","repository_id"),
	CONSTRAINT "plan_repositories_position_unique" UNIQUE("plan_id","position"),
	CONSTRAINT "plan_repositories_position_check" CHECK (("position" >= 0) AND ("position" <= 2))
);
--> statement-breakpoint
CREATE TABLE "app"."plans" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."plans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"repository_id" bigint NOT NULL,
	"todo_id" bigint,
	"title" text NOT NULL,
	"requirements" text NOT NULL,
	"analysis" text,
	"questions" jsonb,
	"answers" jsonb,
	"plan" text,
	"acceptance" jsonb,
	"status" text DEFAULT 'analyzing' NOT NULL,
	"error" text,
	"created_by_login" text,
	"created_by_id" bigint,
	"tier" text,
	"archived" smallint DEFAULT 0 NOT NULL,
	"feedback" text,
	"attachments" jsonb,
	"runner_model" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"feature_id" bigint,
	CONSTRAINT "plans_todo_unique" UNIQUE("todo_id"),
	CONSTRAINT "plans_status_check" CHECK (status = ANY (ARRAY['analyzing'::text, 'awaiting_answers'::text, 'refining'::text, 'plan_ready'::text, 'approving'::text, 'approved'::text, 'failed'::text])),
	CONSTRAINT "plans_archived_check" CHECK (archived = ANY (ARRAY[0, 1]))
);
--> statement-breakpoint
CREATE TABLE "app"."push_subscriptions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."push_subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"user_github_id" bigint NOT NULL,
	"endpoint" text NOT NULL,
	"p256Dh" text NOT NULL,
	"auth" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "push_subscriptions_endpoint_key" UNIQUE("endpoint")
);
--> statement-breakpoint
CREATE TABLE "app"."repo_agents" (
	"repository_id" bigint NOT NULL,
	"agent_id" bigint NOT NULL,
	"installation_id" bigint NOT NULL,
	"enabled" smallint DEFAULT 1 NOT NULL,
	CONSTRAINT "repo_agents_pkey" PRIMARY KEY("repository_id","agent_id"),
	CONSTRAINT "repo_agents_enabled_check" CHECK (enabled = ANY (ARRAY[0, 1]))
);
--> statement-breakpoint
CREATE TABLE "app"."repo_connections" (
	"repository_id" bigint NOT NULL,
	"connection_id" bigint NOT NULL,
	"installation_id" bigint NOT NULL,
	"reviews" smallint DEFAULT 1 NOT NULL,
	"automations" smallint DEFAULT 1 NOT NULL,
	CONSTRAINT "repo_connections_pkey" PRIMARY KEY("repository_id","connection_id"),
	CONSTRAINT "repo_connections_reviews_check" CHECK (reviews = ANY (ARRAY[0, 1])),
	CONSTRAINT "repo_connections_automations_check" CHECK (automations = ANY (ARRAY[0, 1]))
);
--> statement-breakpoint
CREATE TABLE "app"."repo_skills" (
	"repository_id" bigint NOT NULL,
	"skill_id" bigint NOT NULL,
	"installation_id" bigint NOT NULL,
	"enabled" smallint DEFAULT 1 NOT NULL,
	CONSTRAINT "repo_skills_pkey" PRIMARY KEY("repository_id","skill_id"),
	CONSTRAINT "repo_skills_enabled_check" CHECK (enabled = ANY (ARRAY[0, 1]))
);
--> statement-breakpoint
CREATE TABLE "app"."repositories" (
	"id" bigint PRIMARY KEY DEFAULT nextval('app.native_entity_id_seq'::regclass) NOT NULL,
	"installation_id" bigint NOT NULL,
	"owner" text NOT NULL,
	"name" text NOT NULL,
	"provider" text DEFAULT 'github' NOT NULL,
	"artifacts_repo" text,
	"default_branch" text,
	"last_push_at" timestamp with time zone,
	"enabled" smallint DEFAULT 1 NOT NULL,
	"model" text,
	"review_on_push" smallint DEFAULT 0 NOT NULL,
	"blocking_reviews" smallint DEFAULT 0 NOT NULL,
	"auto_fix" smallint DEFAULT 0 NOT NULL,
	"check_command" text,
	"run_command" text,
	"app_port" integer,
	"auto_merge" smallint DEFAULT 0 NOT NULL,
	"demo_videos" smallint DEFAULT 1 NOT NULL,
	"launchable" smallint,
	"auto_resolve_conflicts" smallint DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "repositories_id_installation_unique" UNIQUE("id","installation_id"),
	CONSTRAINT "repositories_owner_name_unique" UNIQUE("owner","name"),
	CONSTRAINT "repositories_provider_check" CHECK (provider = ANY (ARRAY['github'::text, 'artifacts'::text])),
	CONSTRAINT "repositories_enabled_check" CHECK (enabled = ANY (ARRAY[0, 1])),
	CONSTRAINT "repositories_review_on_push_check" CHECK (review_on_push = ANY (ARRAY[0, 1])),
	CONSTRAINT "repositories_blocking_reviews_check" CHECK (blocking_reviews = ANY (ARRAY[0, 1])),
	CONSTRAINT "repositories_auto_fix_check" CHECK (auto_fix = ANY (ARRAY[0, 1])),
	CONSTRAINT "repositories_app_port_check" CHECK ((app_port >= 1) AND (app_port <= 65535)),
	CONSTRAINT "repositories_auto_merge_check" CHECK (auto_merge = ANY (ARRAY[0, 1])),
	CONSTRAINT "repositories_demo_videos_check" CHECK (demo_videos = ANY (ARRAY[0, 1])),
	CONSTRAINT "repositories_launchable_check" CHECK (launchable = ANY (ARRAY[0, 1])),
	CONSTRAINT "repositories_auto_resolve_conflicts_check" CHECK (auto_resolve_conflicts = ANY (ARRAY[0, 1])),
	CONSTRAINT "repositories_artifacts_shape" CHECK (((provider = 'artifacts'::text) AND (artifacts_repo IS NOT NULL) AND (default_branch IS NOT NULL)) OR ((provider = 'github'::text) AND (artifacts_repo IS NULL)))
);
--> statement-breakpoint
CREATE TABLE "app"."repository_refs" (
	"repository_id" bigint NOT NULL,
	"ref" text NOT NULL,
	"head_sha" text NOT NULL,
	"pushed_at" timestamp with time zone NOT NULL,
	CONSTRAINT "repository_refs_pkey" PRIMARY KEY("repository_id","ref")
);
--> statement-breakpoint
CREATE TABLE "app"."reviews" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."reviews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"repository_id" bigint NOT NULL,
	"installation_id" bigint NOT NULL,
	"pr_number" integer NOT NULL,
	"trigger_event" text NOT NULL,
	"status" text DEFAULT 'completed' NOT NULL,
	"completed_at" timestamp with time zone,
	"review_url" text,
	"input_tokens" bigint DEFAULT 0 NOT NULL,
	"output_tokens" bigint DEFAULT 0 NOT NULL,
	"cache_read_tokens" bigint DEFAULT 0 NOT NULL,
	"cache_write_tokens" bigint DEFAULT 0 NOT NULL,
	"cost_usd" numeric(20, 10) DEFAULT 0 NOT NULL,
	"model" text,
	"agent_slug" text,
	"agent_instance_id" text,
	"risk_tier" text,
	"findings_count" integer,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "reviews_output_tokens_check" CHECK (output_tokens >= 0),
	CONSTRAINT "reviews_cache_read_tokens_check" CHECK (cache_read_tokens >= 0),
	CONSTRAINT "reviews_cache_write_tokens_check" CHECK (cache_write_tokens >= 0),
	CONSTRAINT "reviews_pr_number_check" CHECK (pr_number > 0),
	CONSTRAINT "reviews_status_check" CHECK (status = ANY (ARRAY['running'::text, 'completed'::text, 'failed'::text])),
	CONSTRAINT "reviews_input_tokens_check" CHECK (input_tokens >= 0),
	CONSTRAINT "reviews_cost_usd_check" CHECK (cost_usd >= (0)::numeric),
	CONSTRAINT "reviews_risk_tier_check" CHECK ((risk_tier IS NULL) OR (risk_tier = ANY (ARRAY['trivial'::text, 'lite'::text, 'full'::text]))),
	CONSTRAINT "reviews_findings_count_check" CHECK ((findings_count IS NULL) OR (findings_count >= 0)),
	CONSTRAINT "reviews_completion_shape" CHECK (((status = 'running'::text) AND (completed_at IS NULL)) OR (status <> 'running'::text))
);
--> statement-breakpoint
CREATE TABLE "auth"."session" (
	"id" text PRIMARY KEY NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"token" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	"ipAddress" text,
	"userAgent" text,
	"activeOrganizationId" text,
	"userId" text NOT NULL,
	CONSTRAINT "session_token_key" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "app"."skills" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."skills_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"installation_id" bigint NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"instructions" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "skills_id_installation_unique" UNIQUE("id","installation_id"),
	CONSTRAINT "skills_installation_slug_unique" UNIQUE("installation_id","slug"),
	CONSTRAINT "skills_slug_format" CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text)
);
--> statement-breakpoint
CREATE TABLE "app"."todo_repositories" (
	"todo_id" bigint NOT NULL,
	"repository_id" bigint NOT NULL,
	"position" smallint NOT NULL,
	CONSTRAINT "todo_repositories_pkey" PRIMARY KEY("todo_id","repository_id"),
	CONSTRAINT "todo_repositories_position_unique" UNIQUE("todo_id","position"),
	CONSTRAINT "todo_repositories_position_check" CHECK (("position" >= 0) AND ("position" <= 2))
);
--> statement-breakpoint
CREATE TABLE "app"."todos" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."todos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"installation_id" bigint NOT NULL,
	"title" text NOT NULL,
	"notes" text,
	"created_by_login" text,
	"created_by_id" bigint,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"plan_id" bigint
);
--> statement-breakpoint
CREATE TABLE "auth"."user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"emailVerified" boolean DEFAULT false NOT NULL,
	"image" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	"login" text,
	"githubId" bigint,
	CONSTRAINT "user_email_unique" UNIQUE("email"),
	CONSTRAINT "user_github_id_unique" UNIQUE("githubId")
);
--> statement-breakpoint
CREATE TABLE "app"."user_installation_access" (
	"user_id" text PRIMARY KEY NOT NULL,
	"installation_ids" bigint[] DEFAULT '{}' NOT NULL,
	"verified_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "user_installation_access_no_null_ids" CHECK (array_position(installation_ids, NULL::bigint) IS NULL)
);
--> statement-breakpoint
CREATE TABLE "app"."user_tokens" (
	"user_id" bigint PRIMARY KEY NOT NULL,
	"login" text NOT NULL,
	"refresh_ciphertext" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth"."verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."verifications" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."verifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"feature_id" bigint NOT NULL,
	"status" text DEFAULT 'running' NOT NULL,
	"results" jsonb,
	"summary" text,
	"error" text,
	"demo" jsonb,
	"input_tokens" bigint DEFAULT 0 NOT NULL,
	"output_tokens" bigint DEFAULT 0 NOT NULL,
	"cache_read_tokens" bigint DEFAULT 0 NOT NULL,
	"cache_write_tokens" bigint DEFAULT 0 NOT NULL,
	"cost_usd" numeric(20, 10) DEFAULT 0 NOT NULL,
	"model" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "verifications_status_check" CHECK (status = ANY (ARRAY['running'::text, 'passed'::text, 'failed'::text, 'error'::text, 'skipped'::text])),
	CONSTRAINT "verifications_input_tokens_check" CHECK (input_tokens >= 0),
	CONSTRAINT "verifications_output_tokens_check" CHECK (output_tokens >= 0),
	CONSTRAINT "verifications_cache_read_tokens_check" CHECK (cache_read_tokens >= 0),
	CONSTRAINT "verifications_cache_write_tokens_check" CHECK (cache_write_tokens >= 0),
	CONSTRAINT "verifications_cost_usd_check" CHECK (cost_usd >= (0)::numeric)
);
--> statement-breakpoint
ALTER TABLE "auth"."account" ADD CONSTRAINT "account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agent_runs" ADD CONSTRAINT "agent_runs_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "app"."plans"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agent_runs" ADD CONSTRAINT "agent_runs_feature_id_fkey" FOREIGN KEY ("feature_id") REFERENCES "app"."features"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agent_runs" ADD CONSTRAINT "agent_runs_fix_attempt_id_fkey" FOREIGN KEY ("fix_attempt_id") REFERENCES "app"."fix_attempts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agent_runs" ADD CONSTRAINT "agent_runs_automation_run_id_fkey" FOREIGN KEY ("automation_run_id") REFERENCES "app"."automation_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agents" ADD CONSTRAINT "agents_installation_id_fkey" FOREIGN KEY ("installation_id") REFERENCES "app"."installations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."automation_runs" ADD CONSTRAINT "automation_runs_automation_id_fkey" FOREIGN KEY ("automation_id") REFERENCES "app"."automations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."automations" ADD CONSTRAINT "automations_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "app"."repositories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_request_counters" ADD CONSTRAINT "change_request_counters_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "app"."repositories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_requests" ADD CONSTRAINT "change_requests_feature_id_features_id_fk" FOREIGN KEY ("feature_id") REFERENCES "app"."features"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_requests" ADD CONSTRAINT "change_requests_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "app"."repositories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."chat_messages" ADD CONSTRAINT "chat_messages_feature_id_fkey" FOREIGN KEY ("feature_id") REFERENCES "app"."features"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."cockpit_comments" ADD CONSTRAINT "cockpit_comments_feature_id_fkey" FOREIGN KEY ("feature_id") REFERENCES "app"."features"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."cockpit_comments" ADD CONSTRAINT "cockpit_comments_fix_attempt_id_fkey" FOREIGN KEY ("fix_attempt_id") REFERENCES "app"."fix_attempts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."connections" ADD CONSTRAINT "connections_installation_id_fkey" FOREIGN KEY ("installation_id") REFERENCES "app"."installations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."cr_checks" ADD CONSTRAINT "cr_checks_change_request_id_fkey" FOREIGN KEY ("change_request_id") REFERENCES "app"."change_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."cr_comments" ADD CONSTRAINT "cr_comments_change_request_id_fkey" FOREIGN KEY ("change_request_id") REFERENCES "app"."change_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."features" ADD CONSTRAINT "features_plan_id_plans_id_fk" FOREIGN KEY ("plan_id") REFERENCES "app"."plans"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."features" ADD CONSTRAINT "features_change_request_id_change_requests_id_fk" FOREIGN KEY ("change_request_id") REFERENCES "app"."change_requests"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."features" ADD CONSTRAINT "features_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "app"."repositories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."fix_attempts" ADD CONSTRAINT "fix_attempts_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "app"."repositories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."installation_repo_sync" ADD CONSTRAINT "installation_repo_sync_installation_id_fkey" FOREIGN KEY ("installation_id") REFERENCES "app"."installations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."invitation" ADD CONSTRAINT "invitation_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."invitation" ADD CONSTRAINT "invitation_inviterId_fkey" FOREIGN KEY ("inviterId") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."member" ADD CONSTRAINT "member_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."member" ADD CONSTRAINT "member_userId_fkey" FOREIGN KEY ("userId") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."oauthAccessToken" ADD CONSTRAINT "oauthAccessToken_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "auth"."oauthApplication"("clientId") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."oauthAccessToken" ADD CONSTRAINT "oauthAccessToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."oauthApplication" ADD CONSTRAINT "oauthApplication_userId_fkey" FOREIGN KEY ("userId") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."oauthConsent" ADD CONSTRAINT "oauthConsent_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "auth"."oauthApplication"("clientId") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."oauthConsent" ADD CONSTRAINT "oauthConsent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."organization" ADD CONSTRAINT "organization_installationId_fkey" FOREIGN KEY ("installationId") REFERENCES "app"."installations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."plan_repositories" ADD CONSTRAINT "plan_repositories_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "app"."plans"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."plan_repositories" ADD CONSTRAINT "plan_repositories_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "app"."repositories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."plans" ADD CONSTRAINT "plans_todo_id_todos_id_fk" FOREIGN KEY ("todo_id") REFERENCES "app"."todos"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."plans" ADD CONSTRAINT "plans_feature_id_features_id_fk" FOREIGN KEY ("feature_id") REFERENCES "app"."features"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."plans" ADD CONSTRAINT "plans_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "app"."repositories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."push_subscriptions" ADD CONSTRAINT "push_subscriptions_user_github_id_fkey" FOREIGN KEY ("user_github_id") REFERENCES "auth"."user"("githubId") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repo_agents" ADD CONSTRAINT "repo_agents_repository_tenant_fk" FOREIGN KEY ("repository_id","installation_id") REFERENCES "app"."repositories"("id","installation_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repo_agents" ADD CONSTRAINT "repo_agents_agent_tenant_fk" FOREIGN KEY ("agent_id","installation_id") REFERENCES "app"."agents"("id","installation_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repo_connections" ADD CONSTRAINT "repo_connections_repository_tenant_fk" FOREIGN KEY ("repository_id","installation_id") REFERENCES "app"."repositories"("id","installation_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repo_connections" ADD CONSTRAINT "repo_connections_connection_tenant_fk" FOREIGN KEY ("connection_id","installation_id") REFERENCES "app"."connections"("id","installation_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repo_skills" ADD CONSTRAINT "repo_skills_repository_tenant_fk" FOREIGN KEY ("repository_id","installation_id") REFERENCES "app"."repositories"("id","installation_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repo_skills" ADD CONSTRAINT "repo_skills_skill_tenant_fk" FOREIGN KEY ("skill_id","installation_id") REFERENCES "app"."skills"("id","installation_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repositories" ADD CONSTRAINT "repositories_installation_provider_fk" FOREIGN KEY ("installation_id","provider") REFERENCES "app"."installations"("id","provider") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repository_refs" ADD CONSTRAINT "repository_refs_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "app"."repositories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD CONSTRAINT "reviews_repository_tenant_fk" FOREIGN KEY ("repository_id","installation_id") REFERENCES "app"."repositories"("id","installation_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."session" ADD CONSTRAINT "session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."session" ADD CONSTRAINT "session_active_organization_fk" FOREIGN KEY ("activeOrganizationId") REFERENCES "auth"."organization"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."skills" ADD CONSTRAINT "skills_installation_id_fkey" FOREIGN KEY ("installation_id") REFERENCES "app"."installations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."todo_repositories" ADD CONSTRAINT "todo_repositories_todo_id_fkey" FOREIGN KEY ("todo_id") REFERENCES "app"."todos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."todo_repositories" ADD CONSTRAINT "todo_repositories_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "app"."repositories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."todos" ADD CONSTRAINT "todos_plan_id_plans_id_fk" FOREIGN KEY ("plan_id") REFERENCES "app"."plans"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."todos" ADD CONSTRAINT "todos_installation_id_fkey" FOREIGN KEY ("installation_id") REFERENCES "app"."installations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."user_installation_access" ADD CONSTRAINT "user_installation_access_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."verifications" ADD CONSTRAINT "verifications_feature_id_fkey" FOREIGN KEY ("feature_id") REFERENCES "app"."features"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "auth"."account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "agent_runs_automation_idx" ON "app"."agent_runs" USING btree ("automation_run_id") WHERE (automation_run_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "agent_runs_feature_idx" ON "app"."agent_runs" USING btree ("feature_id") WHERE (feature_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "agent_runs_fix_attempt_idx" ON "app"."agent_runs" USING btree ("fix_attempt_id") WHERE (fix_attempt_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "agent_runs_plan_idx" ON "app"."agent_runs" USING btree ("plan_id") WHERE (plan_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "automation_runs_automation_idx" ON "app"."automation_runs" USING btree ("automation_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "automation_runs_one_running_idx" ON "app"."automation_runs" USING btree ("automation_id") WHERE (status = 'running'::text);--> statement-breakpoint
CREATE INDEX "automations_due_idx" ON "app"."automations" USING btree ("next_run_at") WHERE (enabled = 1);--> statement-breakpoint
CREATE INDEX "automations_repository_idx" ON "app"."automations" USING btree ("repository_id","id");--> statement-breakpoint
CREATE INDEX "change_requests_feature_idx" ON "app"."change_requests" USING btree ("feature_id") WHERE (feature_id IS NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX "change_requests_open_branches_unique" ON "app"."change_requests" USING btree ("repository_id","source_branch","target_branch") WHERE (status = 'open'::text);--> statement-breakpoint
CREATE INDEX "change_requests_repo_status_idx" ON "app"."change_requests" USING btree ("repository_id","status","number" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "chat_messages_feature_idx" ON "app"."chat_messages" USING btree ("feature_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "chat_messages_one_pending_user_idx" ON "app"."chat_messages" USING btree ("feature_id") WHERE ((role = 'user'::text) AND (status = ANY (ARRAY['queued'::text, 'running'::text])));--> statement-breakpoint
CREATE INDEX "cockpit_comments_feature_idx" ON "app"."cockpit_comments" USING btree ("feature_id","id");--> statement-breakpoint
CREATE INDEX "cockpit_comments_fix_attempt_idx" ON "app"."cockpit_comments" USING btree ("fix_attempt_id") WHERE (fix_attempt_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "cr_comments_change_request_idx" ON "app"."cr_comments" USING btree ("change_request_id","id");--> statement-breakpoint
CREATE INDEX "features_change_request_idx" ON "app"."features" USING btree ("change_request_id") WHERE (change_request_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "features_generating_created_idx" ON "app"."features" USING btree ("created_at") WHERE (status = 'generating'::text);--> statement-breakpoint
CREATE INDEX "features_open_pr_idx" ON "app"."features" USING btree ("repository_id","pr_number") WHERE ((status = 'pr_opened'::text) AND (pr_number IS NOT NULL));--> statement-breakpoint
CREATE INDEX "features_plan_idx" ON "app"."features" USING btree ("plan_id") WHERE (plan_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "features_repository_created_idx" ON "app"."features" USING btree ("repository_id","id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "features_repository_pr_idx" ON "app"."features" USING btree ("repository_id","pr_number","id" DESC NULLS LAST) WHERE (pr_number IS NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX "fix_attempts_one_running_idx" ON "app"."fix_attempts" USING btree ("repository_id","pr_number") WHERE (status = 'running'::text);--> statement-breakpoint
CREATE INDEX "fix_attempts_pr_idx" ON "app"."fix_attempts" USING btree ("repository_id","pr_number","id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "installations_installer_idx" ON "app"."installations" USING btree ("installer_github_id") WHERE (installer_github_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "invitation_email_status_idx" ON "auth"."invitation" USING btree ("email","status");--> statement-breakpoint
CREATE INDEX "invitation_inviter_idx" ON "auth"."invitation" USING btree ("inviterId");--> statement-breakpoint
CREATE INDEX "invitation_organization_idx" ON "auth"."invitation" USING btree ("organizationId","status");--> statement-breakpoint
CREATE UNIQUE INDEX "invitation_pending_email_unique" ON "auth"."invitation" USING btree ("organizationId",lower("email")) WHERE (status = 'pending'::text);--> statement-breakpoint
CREATE INDEX "member_user_id_idx" ON "auth"."member" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "oauth_access_token_client_id_idx" ON "auth"."oauthAccessToken" USING btree ("clientId");--> statement-breakpoint
CREATE INDEX "oauth_access_token_expiry_idx" ON "auth"."oauthAccessToken" USING btree ("accessTokenExpiresAt");--> statement-breakpoint
CREATE INDEX "oauth_access_token_user_id_idx" ON "auth"."oauthAccessToken" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "oauth_application_user_id_idx" ON "auth"."oauthApplication" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "oauth_consent_client_id_idx" ON "auth"."oauthConsent" USING btree ("clientId");--> statement-breakpoint
CREATE INDEX "oauth_consent_user_id_idx" ON "auth"."oauthConsent" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "plan_repositories_repository_idx" ON "app"."plan_repositories" USING btree ("repository_id");--> statement-breakpoint
CREATE INDEX "plans_active_idx" ON "app"."plans" USING btree ("repository_id","id" DESC NULLS LAST) WHERE (archived = 0);--> statement-breakpoint
CREATE INDEX "plans_feature_idx" ON "app"."plans" USING btree ("feature_id") WHERE (feature_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "plans_repository_created_idx" ON "app"."plans" USING btree ("repository_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "push_subscriptions_user_idx" ON "app"."push_subscriptions" USING btree ("user_github_id");--> statement-breakpoint
CREATE INDEX "repo_agents_agent_tenant_idx" ON "app"."repo_agents" USING btree ("agent_id","installation_id");--> statement-breakpoint
CREATE INDEX "repo_agents_repository_tenant_idx" ON "app"."repo_agents" USING btree ("repository_id","installation_id");--> statement-breakpoint
CREATE INDEX "repo_connections_connection_tenant_idx" ON "app"."repo_connections" USING btree ("connection_id","installation_id");--> statement-breakpoint
CREATE INDEX "repo_connections_repository_tenant_idx" ON "app"."repo_connections" USING btree ("repository_id","installation_id");--> statement-breakpoint
CREATE INDEX "repo_skills_repository_tenant_idx" ON "app"."repo_skills" USING btree ("repository_id","installation_id");--> statement-breakpoint
CREATE INDEX "repo_skills_skill_tenant_idx" ON "app"."repo_skills" USING btree ("skill_id","installation_id");--> statement-breakpoint
CREATE UNIQUE INDEX "repositories_artifacts_repo_unique" ON "app"."repositories" USING btree ("artifacts_repo") WHERE (artifacts_repo IS NOT NULL);--> statement-breakpoint
CREATE INDEX "repositories_enabled_idx" ON "app"."repositories" USING btree ("installation_id","id") WHERE (enabled = 1);--> statement-breakpoint
CREATE INDEX "repositories_installation_idx" ON "app"."repositories" USING btree ("installation_id","provider","owner","name");--> statement-breakpoint
CREATE INDEX "repository_refs_head_idx" ON "app"."repository_refs" USING btree ("repository_id","head_sha");--> statement-breakpoint
CREATE INDEX "reviews_agent_instance_idx" ON "app"."reviews" USING btree ("agent_instance_id");--> statement-breakpoint
CREATE INDEX "reviews_installation_time_idx" ON "app"."reviews" USING btree ("installation_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "reviews_one_running_instance_idx" ON "app"."reviews" USING btree ("agent_instance_id") WHERE ((status = 'running'::text) AND (agent_instance_id IS NOT NULL));--> statement-breakpoint
CREATE INDEX "reviews_repo_pr_idx" ON "app"."reviews" USING btree ("repository_id","pr_number","id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "reviews_repository_installation_idx" ON "app"."reviews" USING btree ("repository_id","installation_id");--> statement-breakpoint
CREATE INDEX "reviews_running_installation_idx" ON "app"."reviews" USING btree ("installation_id","created_at") WHERE (status = 'running'::text);--> statement-breakpoint
CREATE INDEX "session_active_organization_idx" ON "auth"."session" USING btree ("activeOrganizationId") WHERE ("activeOrganizationId" IS NOT NULL);--> statement-breakpoint
CREATE INDEX "session_expires_at_idx" ON "auth"."session" USING btree ("expiresAt");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "auth"."session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "todo_repositories_repository_idx" ON "app"."todo_repositories" USING btree ("repository_id");--> statement-breakpoint
CREATE INDEX "todos_installation_unplanned_idx" ON "app"."todos" USING btree ("installation_id","id" DESC NULLS LAST) WHERE (plan_id IS NULL);--> statement-breakpoint
CREATE UNIQUE INDEX "todos_plan_unique" ON "app"."todos" USING btree ("plan_id") WHERE (plan_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "verification_expires_at_idx" ON "auth"."verification" USING btree ("expiresAt");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "auth"."verification" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX "verifications_feature_idx" ON "app"."verifications" USING btree ("feature_id","id" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "verifications_one_running_idx" ON "app"."verifications" USING btree ("feature_id") WHERE (status = 'running'::text);--> statement-breakpoint
CREATE INDEX "verifications_running_created_idx" ON "app"."verifications" USING btree ("created_at") WHERE (status = 'running'::text);