CREATE SCHEMA "app";
--> statement-breakpoint
CREATE SCHEMA "auth";
--> statement-breakpoint
CREATE TABLE "app"."acceptance_contracts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."acceptance_contracts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"delivery_id" bigint NOT NULL,
	"version" integer NOT NULL,
	"artifact_id" bigint NOT NULL,
	"status" text DEFAULT 'proposed' NOT NULL,
	"created_by_user_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "acceptance_contracts_delivery_version_unique" UNIQUE("delivery_id","version"),
	CONSTRAINT "acceptance_contracts_version_check" CHECK (version > 0),
	CONSTRAINT "acceptance_contracts_status_check" CHECK (status = ANY (ARRAY['proposed', 'active', 'rejected', 'superseded']))
);
--> statement-breakpoint
CREATE TABLE "auth"."account" (
	"id" text PRIMARY KEY NOT NULL,
	"accountId" text NOT NULL,
	"providerId" text NOT NULL,
	"userId" text NOT NULL,
	"accessToken" text,
	"refreshToken" text,
	"idToken" text,
	"accessTokenExpiresAt" timestamp with time zone,
	"refreshTokenExpiresAt" timestamp with time zone,
	"scope" text,
	"password" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "account_provider_identity_unique" UNIQUE("accountId","providerId")
);
--> statement-breakpoint
CREATE TABLE "app"."agent_runs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."agent_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"stage_run_id" bigint NOT NULL,
	"agent_id" bigint NOT NULL,
	"model_id" bigint NOT NULL,
	"input_artifact_id" bigint NOT NULL,
	"output_artifact_id" bigint,
	"log_artifact_id" bigint,
	"status" text DEFAULT 'queued' NOT NULL,
	"input_tokens" bigint DEFAULT 0 NOT NULL,
	"output_tokens" bigint DEFAULT 0 NOT NULL,
	"cache_read_tokens" bigint DEFAULT 0 NOT NULL,
	"cache_write_tokens" bigint DEFAULT 0 NOT NULL,
	"cost_usd" numeric(20, 10) DEFAULT 0 NOT NULL,
	"error_code" text,
	"error_message" text,
	"idempotency_key" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	CONSTRAINT "agent_runs_id_organization_unique" UNIQUE("id","organization_id"),
	CONSTRAINT "agent_runs_idempotency_unique" UNIQUE("idempotency_key"),
	CONSTRAINT "agent_runs_status_check" CHECK (status = ANY (ARRAY['queued', 'running', 'succeeded', 'failed', 'cancelled'])),
	CONSTRAINT "agent_runs_usage_check" CHECK (input_tokens >= 0 AND output_tokens >= 0 AND cache_read_tokens >= 0 AND cache_write_tokens >= 0 AND cost_usd >= 0)
);
--> statement-breakpoint
CREATE TABLE "app"."agent_skills" (
	"agent_id" bigint NOT NULL,
	"skill_id" bigint NOT NULL,
	"organization_id" text NOT NULL,
	CONSTRAINT "agent_skills_agent_id_skill_id_pk" PRIMARY KEY("agent_id","skill_id")
);
--> statement-breakpoint
CREATE TABLE "app"."agents" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."agents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"definition_key" text NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"instructions_override" text,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "agents_id_organization_unique" UNIQUE("id","organization_id"),
	CONSTRAINT "agents_organization_slug_unique" UNIQUE("organization_id","slug"),
	CONSTRAINT "agents_slug_format" CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);
--> statement-breakpoint
CREATE TABLE "app"."artifacts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."artifacts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"kind" text NOT NULL,
	"schema_version" integer NOT NULL,
	"storage_key" text NOT NULL,
	"content_type" text DEFAULT 'application/json' NOT NULL,
	"content_hash" text NOT NULL,
	"size_bytes" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "artifacts_id_organization_unique" UNIQUE("id","organization_id"),
	CONSTRAINT "artifacts_storage_key_unique" UNIQUE("storage_key"),
	CONSTRAINT "artifacts_schema_version_check" CHECK (schema_version > 0),
	CONSTRAINT "artifacts_size_bytes_check" CHECK (size_bytes >= 0)
);
--> statement-breakpoint
CREATE TABLE "app"."automation_integrations" (
	"automation_id" bigint NOT NULL,
	"integration_id" bigint NOT NULL,
	"organization_id" text NOT NULL,
	CONSTRAINT "automation_integrations_automation_id_integration_id_pk" PRIMARY KEY("automation_id","integration_id")
);
--> statement-breakpoint
CREATE TABLE "app"."automation_skills" (
	"automation_id" bigint NOT NULL,
	"skill_id" bigint NOT NULL,
	"organization_id" text NOT NULL,
	CONSTRAINT "automation_skills_automation_id_skill_id_pk" PRIMARY KEY("automation_id","skill_id")
);
--> statement-breakpoint
CREATE TABLE "app"."automations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."automations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"agent_id" bigint NOT NULL,
	"repository_id" bigint,
	"name" text NOT NULL,
	"schedule" text NOT NULL,
	"timezone" text DEFAULT 'UTC' NOT NULL,
	"input_template" jsonb NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"next_run_at" timestamp with time zone,
	"created_by_user_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "automations_id_organization_unique" UNIQUE("id","organization_id"),
	CONSTRAINT "automations_organization_name_unique" UNIQUE("organization_id","name"),
	CONSTRAINT "automations_input_object_check" CHECK (jsonb_typeof(input_template) = 'object')
);
--> statement-breakpoint
CREATE TABLE "app"."change_checks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."change_checks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"change_revision_id" bigint NOT NULL,
	"organization_id" text NOT NULL,
	"name" text NOT NULL,
	"status" text NOT NULL,
	"conclusion" text,
	"details_url" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "change_checks_revision_name_unique" UNIQUE("change_revision_id","name"),
	CONSTRAINT "change_checks_status_check" CHECK (status = ANY (ARRAY['queued', 'running', 'completed']))
);
--> statement-breakpoint
CREATE TABLE "app"."change_comments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."change_comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"change_id" bigint NOT NULL,
	"organization_id" text NOT NULL,
	"external_id" text,
	"author" text NOT NULL,
	"body" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."change_revisions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."change_revisions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"change_id" bigint NOT NULL,
	"version" integer NOT NULL,
	"base_sha" text NOT NULL,
	"head_sha" text NOT NULL,
	"artifact_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "change_revisions_id_organization_unique" UNIQUE("id","organization_id"),
	CONSTRAINT "change_revisions_change_version_unique" UNIQUE("change_id","version"),
	CONSTRAINT "change_revisions_change_head_unique" UNIQUE("change_id","head_sha"),
	CONSTRAINT "change_revisions_version_check" CHECK (version > 0)
);
--> statement-breakpoint
CREATE TABLE "app"."changes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."changes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"repository_id" bigint NOT NULL,
	"delivery_id" bigint,
	"provider_integration_id" bigint NOT NULL,
	"provider_key" text NOT NULL,
	"number" integer,
	"title" text NOT NULL,
	"source_ref" text NOT NULL,
	"target_ref" text NOT NULL,
	"url" text,
	"origin" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "changes_id_organization_unique" UNIQUE("id","organization_id"),
	CONSTRAINT "changes_provider_key_unique" UNIQUE("provider_integration_id","provider_key"),
	CONSTRAINT "changes_number_check" CHECK (number IS NULL OR number > 0),
	CONSTRAINT "changes_origin_check" CHECK (origin = ANY (ARRAY['human', 'factory', 'automation', 'imported'])),
	CONSTRAINT "changes_status_check" CHECK (status = ANY (ARRAY['open', 'merged', 'closed']))
);
--> statement-breakpoint
CREATE TABLE "app"."deliveries" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."deliveries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"work_item_id" bigint NOT NULL,
	"repository_id" bigint NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	CONSTRAINT "deliveries_id_organization_unique" UNIQUE("id","organization_id"),
	CONSTRAINT "deliveries_work_item_repository_unique" UNIQUE("work_item_id","repository_id"),
	CONSTRAINT "deliveries_status_check" CHECK (status = ANY (ARRAY['pending', 'active', 'completed', 'failed', 'cancelled']))
);
--> statement-breakpoint
CREATE TABLE "app"."delivery_messages" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."delivery_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"delivery_id" bigint NOT NULL,
	"organization_id" text NOT NULL,
	"author_user_id" text,
	"role" text NOT NULL,
	"body" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "delivery_messages_role_check" CHECK (role = ANY (ARRAY['user', 'assistant', 'system']))
);
--> statement-breakpoint
CREATE TABLE "app"."factory_runs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."factory_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"flow_key" text NOT NULL,
	"flow_version" integer NOT NULL,
	"model_id" bigint,
	"work_item_id" bigint,
	"delivery_id" bigint,
	"change_id" bigint,
	"automation_id" bigint,
	"parent_run_id" bigint,
	"trigger" text NOT NULL,
	"actor_user_id" text,
	"status" text DEFAULT 'queued' NOT NULL,
	"idempotency_key" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	CONSTRAINT "factory_runs_id_organization_unique" UNIQUE("id","organization_id"),
	CONSTRAINT "factory_runs_organization_idempotency_unique" UNIQUE("organization_id","idempotency_key"),
	CONSTRAINT "factory_runs_flow_version_check" CHECK (flow_version > 0),
	CONSTRAINT "factory_runs_scope_check" CHECK (num_nonnulls(work_item_id, delivery_id, change_id) = 1),
	CONSTRAINT "factory_runs_status_check" CHECK (status = ANY (ARRAY['queued', 'running', 'waiting', 'succeeded', 'failed', 'cancelled']))
);
--> statement-breakpoint
CREATE TABLE "app"."integrations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."integrations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"kind" text NOT NULL,
	"provider" text NOT NULL,
	"name" text NOT NULL,
	"external_account_id" text,
	"config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"auth_ciphertext" text,
	"auth_expires_at" timestamp with time zone,
	"needs_reauthorization" boolean DEFAULT false NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "integrations_id_organization_unique" UNIQUE("id","organization_id"),
	CONSTRAINT "integrations_organization_name_unique" UNIQUE("organization_id","name"),
	CONSTRAINT "integrations_kind_check" CHECK (kind = ANY (ARRAY['scm', 'artifact_store', 'mcp', 'api'])),
	CONSTRAINT "integrations_config_object_check" CHECK (jsonb_typeof(config) = 'object')
);
--> statement-breakpoint
CREATE TABLE "auth"."invitation" (
	"id" text PRIMARY KEY NOT NULL,
	"organizationId" text NOT NULL,
	"email" text NOT NULL,
	"role" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"inviterId" text NOT NULL,
	CONSTRAINT "invitation_role_check" CHECK (role = ANY (ARRAY['owner', 'admin', 'member'])),
	CONSTRAINT "invitation_status_check" CHECK (status = ANY (ARRAY['pending', 'accepted', 'rejected', 'canceled']))
);
--> statement-breakpoint
CREATE TABLE "app"."lifecycle_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."lifecycle_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"factory_run_id" bigint NOT NULL,
	"stage_run_id" bigint,
	"kind" text NOT NULL,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "lifecycle_events_payload_object_check" CHECK (jsonb_typeof(payload) = 'object')
);
--> statement-breakpoint
CREATE TABLE "auth"."member" (
	"id" text PRIMARY KEY NOT NULL,
	"organizationId" text NOT NULL,
	"userId" text NOT NULL,
	"role" text DEFAULT 'member' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "member_organization_user_unique" UNIQUE("organizationId","userId"),
	CONSTRAINT "member_role_check" CHECK (role = ANY (ARRAY['owner', 'admin', 'member']))
);
--> statement-breakpoint
CREATE TABLE "app"."models" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."models_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"provider" text NOT NULL,
	"model_id" text NOT NULL,
	"label" text NOT NULL,
	"capabilities" text[] DEFAULT '{}' NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"is_fast_default" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "models_provider_model_unique" UNIQUE("provider","model_id")
);
--> statement-breakpoint
CREATE TABLE "auth"."oauthAccessToken" (
	"id" text PRIMARY KEY NOT NULL,
	"accessToken" text NOT NULL,
	"refreshToken" text,
	"accessTokenExpiresAt" timestamp with time zone NOT NULL,
	"refreshTokenExpiresAt" timestamp with time zone NOT NULL,
	"clientId" text NOT NULL,
	"userId" text,
	"scopes" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "oauthAccessToken_accessToken_key" UNIQUE("accessToken"),
	CONSTRAINT "oauthAccessToken_refreshToken_key" UNIQUE("refreshToken")
);
--> statement-breakpoint
CREATE TABLE "auth"."oauthApplication" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text,
	"icon" text,
	"metadata" text,
	"clientId" text NOT NULL,
	"clientSecret" text,
	"redirectUrls" text NOT NULL,
	"type" text NOT NULL,
	"disabled" boolean DEFAULT false NOT NULL,
	"userId" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "oauthApplication_clientId_key" UNIQUE("clientId")
);
--> statement-breakpoint
CREATE TABLE "auth"."oauthConsent" (
	"id" text PRIMARY KEY NOT NULL,
	"clientId" text NOT NULL,
	"userId" text NOT NULL,
	"scopes" text NOT NULL,
	"consentGiven" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "oauth_consent_client_user_unique" UNIQUE("clientId","userId")
);
--> statement-breakpoint
CREATE TABLE "auth"."organization" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"logo" text,
	"metadata" text,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "organization_slug_key" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "app"."push_subscriptions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."push_subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"endpoint" text NOT NULL,
	"p256dh" text NOT NULL,
	"auth" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "push_subscriptions_endpoint_unique" UNIQUE("endpoint")
);
--> statement-breakpoint
CREATE TABLE "app"."repositories" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."repositories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"source_integration_id" bigint NOT NULL,
	"external_id" text,
	"owner" text NOT NULL,
	"name" text NOT NULL,
	"default_branch" text,
	"enabled" boolean DEFAULT true NOT NULL,
	"settings" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "repositories_id_organization_unique" UNIQUE("id","organization_id"),
	CONSTRAINT "repositories_source_owner_name_unique" UNIQUE("source_integration_id","owner","name"),
	CONSTRAINT "repositories_settings_object_check" CHECK (jsonb_typeof(settings) = 'object')
);
--> statement-breakpoint
CREATE TABLE "app"."repository_agents" (
	"repository_id" bigint NOT NULL,
	"agent_id" bigint NOT NULL,
	"organization_id" text NOT NULL,
	CONSTRAINT "repository_agents_repository_id_agent_id_pk" PRIMARY KEY("repository_id","agent_id")
);
--> statement-breakpoint
CREATE TABLE "app"."repository_integrations" (
	"repository_id" bigint NOT NULL,
	"integration_id" bigint NOT NULL,
	"organization_id" text NOT NULL,
	CONSTRAINT "repository_integrations_repository_id_integration_id_pk" PRIMARY KEY("repository_id","integration_id")
);
--> statement-breakpoint
CREATE TABLE "app"."repository_refs" (
	"repository_id" bigint NOT NULL,
	"organization_id" text NOT NULL,
	"ref" text NOT NULL,
	"head_sha" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "repository_refs_repository_id_ref_pk" PRIMARY KEY("repository_id","ref")
);
--> statement-breakpoint
CREATE TABLE "app"."repository_skills" (
	"repository_id" bigint NOT NULL,
	"skill_id" bigint NOT NULL,
	"organization_id" text NOT NULL,
	CONSTRAINT "repository_skills_repository_id_skill_id_pk" PRIMARY KEY("repository_id","skill_id")
);
--> statement-breakpoint
CREATE TABLE "app"."review_outcomes" (
	"agent_run_id" bigint PRIMARY KEY NOT NULL,
	"organization_id" text NOT NULL,
	"change_revision_id" bigint NOT NULL,
	"verdict" text NOT NULL,
	"conclusion" text NOT NULL,
	"coverage_status" text NOT NULL,
	"finding_count" integer NOT NULL,
	"publication_url" text,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "review_outcomes_verdict_check" CHECK (verdict = ANY (ARRAY['approve', 'comment', 'request_changes'])),
	CONSTRAINT "review_outcomes_conclusion_check" CHECK (conclusion = ANY (ARRAY['ready', 'ready_with_warnings', 'not_ready', 'inconclusive'])),
	CONSTRAINT "review_outcomes_coverage_status_check" CHECK (coverage_status = ANY (ARRAY['complete', 'incomplete', 'stale'])),
	CONSTRAINT "review_outcomes_finding_count_check" CHECK (finding_count >= 0)
);
--> statement-breakpoint
CREATE TABLE "auth"."session" (
	"id" text PRIMARY KEY NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"token" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	"ipAddress" text,
	"userAgent" text,
	"activeOrganizationId" text,
	"userId" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "app"."skills" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."skills_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"content" text NOT NULL,
	"content_hash" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "skills_id_organization_unique" UNIQUE("id","organization_id"),
	CONSTRAINT "skills_organization_slug_unique" UNIQUE("organization_id","slug"),
	CONSTRAINT "skills_slug_format" CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);
--> statement-breakpoint
CREATE TABLE "app"."stage_runs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."stage_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"factory_run_id" bigint NOT NULL,
	"stage_key" text NOT NULL,
	"attempt" integer DEFAULT 1 NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"idempotency_key" text NOT NULL,
	"error_code" text,
	"error_message" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	CONSTRAINT "stage_runs_id_organization_unique" UNIQUE("id","organization_id"),
	CONSTRAINT "stage_runs_id_factory_organization_unique" UNIQUE("id","factory_run_id","organization_id"),
	CONSTRAINT "stage_runs_factory_stage_attempt_unique" UNIQUE("factory_run_id","stage_key","attempt"),
	CONSTRAINT "stage_runs_idempotency_unique" UNIQUE("idempotency_key"),
	CONSTRAINT "stage_runs_attempt_check" CHECK (attempt > 0),
	CONSTRAINT "stage_runs_status_check" CHECK (status = ANY (ARRAY['queued', 'running', 'waiting', 'succeeded', 'failed', 'skipped', 'cancelled']))
);
--> statement-breakpoint
CREATE TABLE "auth"."user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"emailVerified" boolean DEFAULT false NOT NULL,
	"image" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	"login" text,
	"githubId" bigint,
	CONSTRAINT "user_email_unique" UNIQUE("email"),
	CONSTRAINT "user_github_id_unique" UNIQUE("githubId")
);
--> statement-breakpoint
CREATE TABLE "auth"."verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."work_item_targets" (
	"work_item_id" bigint NOT NULL,
	"repository_id" bigint NOT NULL,
	"organization_id" text NOT NULL,
	"position" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "work_item_targets_work_item_id_repository_id_pk" PRIMARY KEY("work_item_id","repository_id"),
	CONSTRAINT "work_item_targets_scope_unique" UNIQUE("work_item_id","repository_id","organization_id"),
	CONSTRAINT "work_item_targets_position_unique" UNIQUE("work_item_id","position"),
	CONSTRAINT "work_item_targets_position_check" CHECK (position >= 0 AND position < 3)
);
--> statement-breakpoint
CREATE TABLE "app"."work_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."work_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"origin" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"approved_plan_artifact_id" bigint,
	"created_by_user_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	CONSTRAINT "work_items_id_organization_unique" UNIQUE("id","organization_id"),
	CONSTRAINT "work_items_origin_check" CHECK (origin = ANY (ARRAY['idea', 'issue', 'external_change', 'automation', 'api'])),
	CONSTRAINT "work_items_status_check" CHECK (status = ANY (ARRAY['open', 'planning', 'awaiting_approval', 'approved', 'in_progress', 'completed', 'cancelled']))
);
--> statement-breakpoint
ALTER TABLE "app"."acceptance_contracts" ADD CONSTRAINT "acceptance_contracts_delivery_id_organization_id_deliveries_id_organization_id_fk" FOREIGN KEY ("delivery_id","organization_id") REFERENCES "app"."deliveries"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."acceptance_contracts" ADD CONSTRAINT "acceptance_contracts_artifact_id_organization_id_artifacts_id_organization_id_fk" FOREIGN KEY ("artifact_id","organization_id") REFERENCES "app"."artifacts"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."acceptance_contracts" ADD CONSTRAINT "acceptance_contracts_created_by_user_id_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."account" ADD CONSTRAINT "account_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agent_runs" ADD CONSTRAINT "agent_runs_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agent_runs" ADD CONSTRAINT "agent_runs_stage_run_id_organization_id_stage_runs_id_organization_id_fk" FOREIGN KEY ("stage_run_id","organization_id") REFERENCES "app"."stage_runs"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agent_runs" ADD CONSTRAINT "agent_runs_agent_id_organization_id_agents_id_organization_id_fk" FOREIGN KEY ("agent_id","organization_id") REFERENCES "app"."agents"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agent_runs" ADD CONSTRAINT "agent_runs_model_id_models_id_fk" FOREIGN KEY ("model_id") REFERENCES "app"."models"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agent_runs" ADD CONSTRAINT "agent_runs_input_artifact_id_organization_id_artifacts_id_organization_id_fk" FOREIGN KEY ("input_artifact_id","organization_id") REFERENCES "app"."artifacts"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agent_runs" ADD CONSTRAINT "agent_runs_output_artifact_id_organization_id_artifacts_id_organization_id_fk" FOREIGN KEY ("output_artifact_id","organization_id") REFERENCES "app"."artifacts"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agent_runs" ADD CONSTRAINT "agent_runs_log_artifact_id_organization_id_artifacts_id_organization_id_fk" FOREIGN KEY ("log_artifact_id","organization_id") REFERENCES "app"."artifacts"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agent_skills" ADD CONSTRAINT "agent_skills_agent_id_organization_id_agents_id_organization_id_fk" FOREIGN KEY ("agent_id","organization_id") REFERENCES "app"."agents"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agent_skills" ADD CONSTRAINT "agent_skills_skill_id_organization_id_skills_id_organization_id_fk" FOREIGN KEY ("skill_id","organization_id") REFERENCES "app"."skills"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."agents" ADD CONSTRAINT "agents_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."artifacts" ADD CONSTRAINT "artifacts_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."automation_integrations" ADD CONSTRAINT "automation_integrations_automation_id_organization_id_automations_id_organization_id_fk" FOREIGN KEY ("automation_id","organization_id") REFERENCES "app"."automations"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."automation_integrations" ADD CONSTRAINT "automation_integrations_integration_id_organization_id_integrations_id_organization_id_fk" FOREIGN KEY ("integration_id","organization_id") REFERENCES "app"."integrations"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."automation_skills" ADD CONSTRAINT "automation_skills_automation_id_organization_id_automations_id_organization_id_fk" FOREIGN KEY ("automation_id","organization_id") REFERENCES "app"."automations"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."automation_skills" ADD CONSTRAINT "automation_skills_skill_id_organization_id_skills_id_organization_id_fk" FOREIGN KEY ("skill_id","organization_id") REFERENCES "app"."skills"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."automations" ADD CONSTRAINT "automations_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."automations" ADD CONSTRAINT "automations_agent_id_organization_id_agents_id_organization_id_fk" FOREIGN KEY ("agent_id","organization_id") REFERENCES "app"."agents"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."automations" ADD CONSTRAINT "automations_repository_id_organization_id_repositories_id_organization_id_fk" FOREIGN KEY ("repository_id","organization_id") REFERENCES "app"."repositories"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."automations" ADD CONSTRAINT "automations_created_by_user_id_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "auth"."user"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_checks" ADD CONSTRAINT "change_checks_change_revision_id_organization_id_change_revisions_id_organization_id_fk" FOREIGN KEY ("change_revision_id","organization_id") REFERENCES "app"."change_revisions"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_comments" ADD CONSTRAINT "change_comments_change_id_organization_id_changes_id_organization_id_fk" FOREIGN KEY ("change_id","organization_id") REFERENCES "app"."changes"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_revisions" ADD CONSTRAINT "change_revisions_change_id_organization_id_changes_id_organization_id_fk" FOREIGN KEY ("change_id","organization_id") REFERENCES "app"."changes"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_revisions" ADD CONSTRAINT "change_revisions_artifact_id_organization_id_artifacts_id_organization_id_fk" FOREIGN KEY ("artifact_id","organization_id") REFERENCES "app"."artifacts"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."changes" ADD CONSTRAINT "changes_repository_id_organization_id_repositories_id_organization_id_fk" FOREIGN KEY ("repository_id","organization_id") REFERENCES "app"."repositories"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."changes" ADD CONSTRAINT "changes_delivery_id_organization_id_deliveries_id_organization_id_fk" FOREIGN KEY ("delivery_id","organization_id") REFERENCES "app"."deliveries"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."changes" ADD CONSTRAINT "changes_provider_integration_id_organization_id_integrations_id_organization_id_fk" FOREIGN KEY ("provider_integration_id","organization_id") REFERENCES "app"."integrations"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."deliveries" ADD CONSTRAINT "deliveries_work_item_id_repository_id_organization_id_work_item_targets_work_item_id_repository_id_organization_id_fk" FOREIGN KEY ("work_item_id","repository_id","organization_id") REFERENCES "app"."work_item_targets"("work_item_id","repository_id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."delivery_messages" ADD CONSTRAINT "delivery_messages_delivery_id_organization_id_deliveries_id_organization_id_fk" FOREIGN KEY ("delivery_id","organization_id") REFERENCES "app"."deliveries"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."delivery_messages" ADD CONSTRAINT "delivery_messages_author_user_id_user_id_fk" FOREIGN KEY ("author_user_id") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."factory_runs" ADD CONSTRAINT "factory_runs_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."factory_runs" ADD CONSTRAINT "factory_runs_model_id_models_id_fk" FOREIGN KEY ("model_id") REFERENCES "app"."models"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."factory_runs" ADD CONSTRAINT "factory_runs_parent_run_id_organization_id_factory_runs_id_organization_id_fk" FOREIGN KEY ("parent_run_id","organization_id") REFERENCES "app"."factory_runs"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."factory_runs" ADD CONSTRAINT "factory_runs_work_item_id_organization_id_work_items_id_organization_id_fk" FOREIGN KEY ("work_item_id","organization_id") REFERENCES "app"."work_items"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."factory_runs" ADD CONSTRAINT "factory_runs_delivery_id_organization_id_deliveries_id_organization_id_fk" FOREIGN KEY ("delivery_id","organization_id") REFERENCES "app"."deliveries"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."factory_runs" ADD CONSTRAINT "factory_runs_change_id_organization_id_changes_id_organization_id_fk" FOREIGN KEY ("change_id","organization_id") REFERENCES "app"."changes"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."factory_runs" ADD CONSTRAINT "factory_runs_automation_id_organization_id_automations_id_organization_id_fk" FOREIGN KEY ("automation_id","organization_id") REFERENCES "app"."automations"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."factory_runs" ADD CONSTRAINT "factory_runs_actor_user_id_user_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."integrations" ADD CONSTRAINT "integrations_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."invitation" ADD CONSTRAINT "invitation_organizationId_organization_id_fk" FOREIGN KEY ("organizationId") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."invitation" ADD CONSTRAINT "invitation_inviterId_user_id_fk" FOREIGN KEY ("inviterId") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."lifecycle_events" ADD CONSTRAINT "lifecycle_events_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."lifecycle_events" ADD CONSTRAINT "lifecycle_events_factory_run_id_organization_id_factory_runs_id_organization_id_fk" FOREIGN KEY ("factory_run_id","organization_id") REFERENCES "app"."factory_runs"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."lifecycle_events" ADD CONSTRAINT "lifecycle_events_stage_run_id_factory_run_id_organization_id_stage_runs_id_factory_run_id_organization_id_fk" FOREIGN KEY ("stage_run_id","factory_run_id","organization_id") REFERENCES "app"."stage_runs"("id","factory_run_id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."member" ADD CONSTRAINT "member_organizationId_organization_id_fk" FOREIGN KEY ("organizationId") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."member" ADD CONSTRAINT "member_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."oauthAccessToken" ADD CONSTRAINT "oauthAccessToken_clientId_oauthApplication_clientId_fk" FOREIGN KEY ("clientId") REFERENCES "auth"."oauthApplication"("clientId") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."oauthAccessToken" ADD CONSTRAINT "oauthAccessToken_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."oauthApplication" ADD CONSTRAINT "oauthApplication_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."oauthConsent" ADD CONSTRAINT "oauthConsent_clientId_oauthApplication_clientId_fk" FOREIGN KEY ("clientId") REFERENCES "auth"."oauthApplication"("clientId") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."oauthConsent" ADD CONSTRAINT "oauthConsent_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."push_subscriptions" ADD CONSTRAINT "push_subscriptions_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repositories" ADD CONSTRAINT "repositories_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repositories" ADD CONSTRAINT "repositories_source_integration_id_organization_id_integrations_id_organization_id_fk" FOREIGN KEY ("source_integration_id","organization_id") REFERENCES "app"."integrations"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repository_agents" ADD CONSTRAINT "repository_agents_repository_id_organization_id_repositories_id_organization_id_fk" FOREIGN KEY ("repository_id","organization_id") REFERENCES "app"."repositories"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repository_agents" ADD CONSTRAINT "repository_agents_agent_id_organization_id_agents_id_organization_id_fk" FOREIGN KEY ("agent_id","organization_id") REFERENCES "app"."agents"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repository_integrations" ADD CONSTRAINT "repository_integrations_repository_id_organization_id_repositories_id_organization_id_fk" FOREIGN KEY ("repository_id","organization_id") REFERENCES "app"."repositories"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repository_integrations" ADD CONSTRAINT "repository_integrations_integration_id_organization_id_integrations_id_organization_id_fk" FOREIGN KEY ("integration_id","organization_id") REFERENCES "app"."integrations"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repository_refs" ADD CONSTRAINT "repository_refs_repository_id_organization_id_repositories_id_organization_id_fk" FOREIGN KEY ("repository_id","organization_id") REFERENCES "app"."repositories"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repository_skills" ADD CONSTRAINT "repository_skills_repository_id_organization_id_repositories_id_organization_id_fk" FOREIGN KEY ("repository_id","organization_id") REFERENCES "app"."repositories"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."repository_skills" ADD CONSTRAINT "repository_skills_skill_id_organization_id_skills_id_organization_id_fk" FOREIGN KEY ("skill_id","organization_id") REFERENCES "app"."skills"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."review_outcomes" ADD CONSTRAINT "review_outcomes_agent_run_id_organization_id_agent_runs_id_organization_id_fk" FOREIGN KEY ("agent_run_id","organization_id") REFERENCES "app"."agent_runs"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."review_outcomes" ADD CONSTRAINT "review_outcomes_change_revision_id_organization_id_change_revisions_id_organization_id_fk" FOREIGN KEY ("change_revision_id","organization_id") REFERENCES "app"."change_revisions"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."session" ADD CONSTRAINT "session_active_organization_fkey" FOREIGN KEY ("activeOrganizationId") REFERENCES "auth"."organization"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."session" ADD CONSTRAINT "session_user_id_fkey" FOREIGN KEY ("userId") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."skills" ADD CONSTRAINT "skills_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."stage_runs" ADD CONSTRAINT "stage_runs_factory_run_id_organization_id_factory_runs_id_organization_id_fk" FOREIGN KEY ("factory_run_id","organization_id") REFERENCES "app"."factory_runs"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."work_item_targets" ADD CONSTRAINT "work_item_targets_work_item_id_organization_id_work_items_id_organization_id_fk" FOREIGN KEY ("work_item_id","organization_id") REFERENCES "app"."work_items"("id","organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."work_item_targets" ADD CONSTRAINT "work_item_targets_repository_id_organization_id_repositories_id_organization_id_fk" FOREIGN KEY ("repository_id","organization_id") REFERENCES "app"."repositories"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."work_items" ADD CONSTRAINT "work_items_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."work_items" ADD CONSTRAINT "work_items_approved_plan_artifact_id_organization_id_artifacts_id_organization_id_fk" FOREIGN KEY ("approved_plan_artifact_id","organization_id") REFERENCES "app"."artifacts"("id","organization_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."work_items" ADD CONSTRAINT "work_items_created_by_user_id_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "acceptance_contracts_artifact_idx" ON "app"."acceptance_contracts" USING btree ("artifact_id");--> statement-breakpoint
CREATE INDEX "acceptance_contracts_creator_idx" ON "app"."acceptance_contracts" USING btree ("created_by_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "acceptance_contracts_one_active_unique" ON "app"."acceptance_contracts" USING btree ("delivery_id") WHERE status = 'active';--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "auth"."account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "agent_runs_stage_run_idx" ON "app"."agent_runs" USING btree ("stage_run_id","id");--> statement-breakpoint
CREATE INDEX "agent_runs_agent_idx" ON "app"."agent_runs" USING btree ("agent_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "agent_runs_model_idx" ON "app"."agent_runs" USING btree ("model_id");--> statement-breakpoint
CREATE INDEX "agent_runs_input_artifact_idx" ON "app"."agent_runs" USING btree ("input_artifact_id");--> statement-breakpoint
CREATE INDEX "agent_runs_log_artifact_idx" ON "app"."agent_runs" USING btree ("log_artifact_id");--> statement-breakpoint
CREATE INDEX "agent_runs_organization_idx" ON "app"."agent_runs" USING btree ("organization_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "agent_runs_output_artifact_unique" ON "app"."agent_runs" USING btree ("output_artifact_id") WHERE output_artifact_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX "agent_skills_skill_idx" ON "app"."agent_skills" USING btree ("skill_id");--> statement-breakpoint
CREATE INDEX "agents_organization_definition_idx" ON "app"."agents" USING btree ("organization_id","definition_key");--> statement-breakpoint
CREATE INDEX "artifacts_organization_kind_idx" ON "app"."artifacts" USING btree ("organization_id","kind","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "automation_integrations_integration_idx" ON "app"."automation_integrations" USING btree ("integration_id");--> statement-breakpoint
CREATE INDEX "automation_skills_skill_idx" ON "app"."automation_skills" USING btree ("skill_id");--> statement-breakpoint
CREATE INDEX "automations_agent_idx" ON "app"."automations" USING btree ("agent_id");--> statement-breakpoint
CREATE INDEX "automations_due_idx" ON "app"."automations" USING btree ("next_run_at") WHERE enabled;--> statement-breakpoint
CREATE INDEX "automations_repository_idx" ON "app"."automations" USING btree ("repository_id");--> statement-breakpoint
CREATE INDEX "automations_creator_idx" ON "app"."automations" USING btree ("created_by_user_id");--> statement-breakpoint
CREATE INDEX "change_checks_revision_idx" ON "app"."change_checks" USING btree ("change_revision_id");--> statement-breakpoint
CREATE INDEX "change_comments_change_idx" ON "app"."change_comments" USING btree ("change_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "change_comments_external_id_unique" ON "app"."change_comments" USING btree ("change_id","external_id") WHERE external_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX "change_revisions_artifact_idx" ON "app"."change_revisions" USING btree ("artifact_id");--> statement-breakpoint
CREATE INDEX "changes_repository_status_idx" ON "app"."changes" USING btree ("repository_id","status","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "changes_delivery_unique" ON "app"."changes" USING btree ("delivery_id") WHERE delivery_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX "deliveries_organization_created_idx" ON "app"."deliveries" USING btree ("organization_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "deliveries_repository_idx" ON "app"."deliveries" USING btree ("repository_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "delivery_messages_delivery_idx" ON "app"."delivery_messages" USING btree ("delivery_id","id");--> statement-breakpoint
CREATE INDEX "delivery_messages_author_idx" ON "app"."delivery_messages" USING btree ("author_user_id");--> statement-breakpoint
CREATE INDEX "factory_runs_work_item_idx" ON "app"."factory_runs" USING btree ("work_item_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "factory_runs_delivery_idx" ON "app"."factory_runs" USING btree ("delivery_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "factory_runs_change_idx" ON "app"."factory_runs" USING btree ("change_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "factory_runs_automation_idx" ON "app"."factory_runs" USING btree ("automation_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "factory_runs_parent_idx" ON "app"."factory_runs" USING btree ("parent_run_id");--> statement-breakpoint
CREATE INDEX "factory_runs_actor_idx" ON "app"."factory_runs" USING btree ("actor_user_id");--> statement-breakpoint
CREATE INDEX "factory_runs_model_idx" ON "app"."factory_runs" USING btree ("model_id");--> statement-breakpoint
CREATE INDEX "integrations_organization_kind_idx" ON "app"."integrations" USING btree ("organization_id","kind");--> statement-breakpoint
CREATE UNIQUE INDEX "integrations_external_account_unique" ON "app"."integrations" USING btree ("provider","external_account_id") WHERE external_account_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX "invitation_email_status_idx" ON "auth"."invitation" USING btree ("email","status");--> statement-breakpoint
CREATE INDEX "invitation_inviter_idx" ON "auth"."invitation" USING btree ("inviterId");--> statement-breakpoint
CREATE INDEX "invitation_organization_idx" ON "auth"."invitation" USING btree ("organizationId","status");--> statement-breakpoint
CREATE UNIQUE INDEX "invitation_pending_email_unique" ON "auth"."invitation" USING btree ("organizationId",lower("email")) WHERE status = 'pending';--> statement-breakpoint
CREATE INDEX "lifecycle_events_factory_run_idx" ON "app"."lifecycle_events" USING btree ("factory_run_id","id");--> statement-breakpoint
CREATE INDEX "lifecycle_events_stage_run_idx" ON "app"."lifecycle_events" USING btree ("stage_run_id");--> statement-breakpoint
CREATE INDEX "lifecycle_events_organization_idx" ON "app"."lifecycle_events" USING btree ("organization_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "member_user_id_idx" ON "auth"."member" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "models_default_unique" ON "app"."models" USING btree ("is_default") WHERE is_default;--> statement-breakpoint
CREATE UNIQUE INDEX "models_fast_default_unique" ON "app"."models" USING btree ("is_fast_default") WHERE is_fast_default;--> statement-breakpoint
CREATE INDEX "oauth_access_token_client_id_idx" ON "auth"."oauthAccessToken" USING btree ("clientId");--> statement-breakpoint
CREATE INDEX "oauth_access_token_expiry_idx" ON "auth"."oauthAccessToken" USING btree ("accessTokenExpiresAt");--> statement-breakpoint
CREATE INDEX "oauth_access_token_user_id_idx" ON "auth"."oauthAccessToken" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "oauth_application_user_id_idx" ON "auth"."oauthApplication" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "oauth_consent_client_id_idx" ON "auth"."oauthConsent" USING btree ("clientId");--> statement-breakpoint
CREATE INDEX "oauth_consent_user_id_idx" ON "auth"."oauthConsent" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "push_subscriptions_user_idx" ON "app"."push_subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "repositories_source_integration_idx" ON "app"."repositories" USING btree ("source_integration_id");--> statement-breakpoint
CREATE INDEX "repositories_organization_idx" ON "app"."repositories" USING btree ("organization_id","owner","name");--> statement-breakpoint
CREATE UNIQUE INDEX "repositories_source_external_unique" ON "app"."repositories" USING btree ("source_integration_id","external_id") WHERE external_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX "repository_agents_agent_idx" ON "app"."repository_agents" USING btree ("agent_id");--> statement-breakpoint
CREATE INDEX "repository_integrations_integration_idx" ON "app"."repository_integrations" USING btree ("integration_id");--> statement-breakpoint
CREATE INDEX "repository_skills_skill_idx" ON "app"."repository_skills" USING btree ("skill_id");--> statement-breakpoint
CREATE INDEX "review_outcomes_change_revision_idx" ON "app"."review_outcomes" USING btree ("change_revision_id","agent_run_id");--> statement-breakpoint
CREATE INDEX "session_active_organization_idx" ON "auth"."session" USING btree ("activeOrganizationId");--> statement-breakpoint
CREATE INDEX "session_expires_at_idx" ON "auth"."session" USING btree ("expiresAt");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "auth"."session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "stage_runs_factory_run_idx" ON "app"."stage_runs" USING btree ("factory_run_id","id");--> statement-breakpoint
CREATE INDEX "verification_expires_at_idx" ON "auth"."verification" USING btree ("expiresAt");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "auth"."verification" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX "work_item_targets_repository_idx" ON "app"."work_item_targets" USING btree ("repository_id");--> statement-breakpoint
CREATE INDEX "work_items_organization_created_idx" ON "app"."work_items" USING btree ("organization_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "work_items_approved_plan_idx" ON "app"."work_items" USING btree ("approved_plan_artifact_id");--> statement-breakpoint
CREATE INDEX "work_items_creator_idx" ON "app"."work_items" USING btree ("created_by_user_id");--> statement-breakpoint
INSERT INTO "app"."models"
  ("provider", "model_id", "label", "capabilities", "enabled", "is_default", "is_fast_default")
VALUES
  ('openai', 'gpt-5.6-sol', 'GPT-5.6 Sol', ARRAY['text', 'tools', 'reasoning'], true, true, false),
  ('anthropic', 'claude-opus-4.8', 'Claude Opus 4.8', ARRAY['text', 'tools', 'reasoning'], true, false, true);
