-- Cloudflare AI catalog snapshot (2026-09-18): AI Gateway models tagged
-- "Coding", plus code-specific models hosted on Workers AI.
INSERT INTO "app"."models"
  ("provider", "model_id", "label", "capabilities", "enabled")
VALUES
  ('alibaba', 'qwen3-max', 'Qwen 3 Max', ARRAY['text', 'reasoning'], true),
  ('alibaba', 'qwen3.5-397b-a17b', 'Qwen 3.5 397B A17B', ARRAY['text', 'reasoning'], true),
  ('alibaba', 'qwen3.7-max', 'Qwen 3.7 Max', ARRAY['text', 'tools', 'reasoning'], true),
  ('alibaba', 'qwen3.7-plus', 'Qwen 3.7 Plus', ARRAY['text', 'tools', 'reasoning', 'vision'], true),
  ('alibaba', 'qwen3.8-max', 'Qwen 3.8 Max', ARRAY['text', 'tools', 'reasoning', 'vision'], true),
  ('anthropic', 'claude-fable-5', 'Claude Fable 5', ARRAY['text', 'tools', 'reasoning'], true),
  ('anthropic', 'claude-fable-5.1', 'Claude Fable 5.1', ARRAY['text', 'tools', 'reasoning'], true),
  ('anthropic', 'claude-haiku-4.5', 'Claude Haiku 4.5', ARRAY['text'], true),
  ('anthropic', 'claude-opus-4.5', 'Claude Opus 4.5', ARRAY['text', 'tools', 'reasoning'], true),
  ('anthropic', 'claude-opus-4.6', 'Claude Opus 4.6', ARRAY['text', 'tools', 'reasoning'], true),
  ('anthropic', 'claude-opus-4.7', 'Claude Opus 4.7', ARRAY['text', 'tools', 'reasoning'], true),
  ('anthropic', 'claude-opus-4.8', 'Claude Opus 4.8', ARRAY['text', 'tools', 'reasoning'], true),
  ('anthropic', 'claude-opus-5', 'Claude Opus 5', ARRAY['text', 'tools', 'reasoning'], true),
  ('anthropic', 'claude-sonnet-4.5', 'Claude Sonnet 4.5', ARRAY['text', 'tools', 'reasoning'], true),
  ('anthropic', 'claude-sonnet-4.6', 'Claude Sonnet 4.6', ARRAY['text', 'tools', 'reasoning'], true),
  ('anthropic', 'claude-sonnet-5', 'Claude Sonnet 5', ARRAY['text', 'tools', 'reasoning'], true),
  ('google', 'gemini-3.6-flash', 'Gemini 3.6 Flash', ARRAY['text', 'tools', 'reasoning', 'vision'], true),
  ('google', 'gemini-3.7-flash', 'Gemini 3.7 Flash', ARRAY['text', 'tools', 'reasoning', 'vision'], true),
  ('google', 'gemini-3.8-flash', 'Gemini 3.8 Flash', ARRAY['text', 'tools', 'reasoning', 'vision'], true),
  ('moonshotai', 'kimi-k3', 'Kimi K3', ARRAY['text', 'tools', 'reasoning', 'vision'], true),
  ('openai', 'gpt-4.1', 'GPT-4.1', ARRAY['text', 'reasoning'], true),
  ('openai', 'gpt-5', 'GPT-5', ARRAY['text', 'reasoning'], true),
  ('openai', 'gpt-5.1', 'GPT-5.1', ARRAY['text', 'reasoning'], true),
  ('openai', 'gpt-5.4', 'GPT-5.4', ARRAY['text', 'reasoning', 'vision'], true),
  ('openai', 'gpt-5.4-pro', 'GPT-5.4 pro', ARRAY['text', 'tools', 'reasoning', 'vision'], true),
  ('openai', 'gpt-5.5', 'GPT-5.5', ARRAY['text', 'reasoning', 'vision'], true),
  ('openai', 'gpt-5.5-pro', 'GPT-5.5 pro', ARRAY['text', 'tools', 'reasoning', 'vision'], true),
  ('openai', 'gpt-5.6-luna', 'GPT-5.6 Luna', ARRAY['text', 'tools', 'reasoning', 'vision'], true),
  ('openai', 'gpt-5.6-sol', 'GPT-5.6 Sol', ARRAY['text', 'tools', 'reasoning', 'vision'], true),
  ('openai', 'gpt-5.6-terra', 'GPT-5.6 Terra', ARRAY['text', 'tools', 'reasoning', 'vision'], true),
  ('openai', 'gpt-6-astra', 'GPT-6 Astra', ARRAY['text', 'reasoning', 'vision'], true),
  ('openai', 'o3', 'o3', ARRAY['text', 'reasoning'], true),
  ('stealth', 'union-alpha', 'Union Alpha', ARRAY['text', 'reasoning', 'vision'], true),
  ('thinkingmachines', 'inkling', 'Inkling', ARRAY['text', 'tools', 'reasoning'], true),
  ('thinkingmachines', 'inkling-256k', 'Inkling 256K', ARRAY['text', 'tools', 'reasoning'], true),
  ('unbiased', 'pareto', 'Pareto', ARRAY['text', 'reasoning', 'vision'], true),
  ('xai', 'grok-4.20-0309-non-reasoning', 'Grok 4.20 Non-Reasoning', ARRAY['text'], true),
  ('xai', 'grok-4.20-0309-reasoning', 'Grok 4.20 Reasoning', ARRAY['text', 'tools', 'reasoning'], true),
  ('xai', 'grok-4.3', 'Grok 4.3', ARRAY['text', 'tools', 'reasoning', 'vision'], true),
  ('cloudflare', '@cf/moonshotai/kimi-k2.7-code', 'Kimi K2.7 Code', ARRAY['text', 'tools', 'reasoning', 'vision'], true),
  ('cloudflare', '@cf/qwen/qwen2.5-coder-32b-instruct', 'Qwen2.5 Coder 32B Instruct', ARRAY['text'], true),
  ('cloudflare', '@cf/zai-org/glm-5.2', 'GLM-5.2', ARRAY['text', 'tools', 'reasoning'], true),
  ('cloudflare', '@cf/zai-org/glm-5.3', 'GLM-5.3', ARRAY['text', 'tools', 'reasoning'], true),
  ('cloudflare', '@cf/zai-org/glm-5.3-flash', 'GLM-5.3 Flash', ARRAY['text', 'tools', 'reasoning', 'vision'], true)
ON CONFLICT ("provider", "model_id") DO UPDATE SET
  "label" = EXCLUDED."label",
  "capabilities" = EXCLUDED."capabilities",
  "enabled" = EXCLUDED."enabled";
