CREATE TABLE app.installations (
  id bigint PRIMARY KEY DEFAULT nextval('app.native_entity_id_seq'),
  account_login text NOT NULL,
  account_id bigint NOT NULL,
  account_type text NOT NULL CHECK (account_type IN ('Organization', 'User')),
  suspended smallint NOT NULL DEFAULT 0 CHECK (suspended IN (0, 1)),
  provider text NOT NULL DEFAULT 'github' CHECK (provider IN ('github', 'artifacts')),
  installer_github_id bigint,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT installations_id_provider_unique UNIQUE (id, provider),
  CONSTRAINT installations_provider_account_unique UNIQUE (provider, account_id),
  CONSTRAINT installations_provider_login_unique UNIQUE (provider, account_login)
);

CREATE INDEX installations_installer_idx ON app.installations (installer_github_id)
  WHERE installer_github_id IS NOT NULL;

CREATE TABLE app.repositories (
  id bigint PRIMARY KEY DEFAULT nextval('app.native_entity_id_seq'),
  installation_id bigint NOT NULL,
  owner text NOT NULL,
  name text NOT NULL,
  provider text NOT NULL DEFAULT 'github' CHECK (provider IN ('github', 'artifacts')),
  artifacts_repo text,
  default_branch text,
  last_push_at timestamptz,
  enabled smallint NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  model text,
  review_on_push smallint NOT NULL DEFAULT 0 CHECK (review_on_push IN (0, 1)),
  blocking_reviews smallint NOT NULL DEFAULT 0 CHECK (blocking_reviews IN (0, 1)),
  auto_fix smallint NOT NULL DEFAULT 0 CHECK (auto_fix IN (0, 1)),
  check_command text,
  run_command text,
  app_port integer CHECK (app_port BETWEEN 1 AND 65535),
  auto_merge smallint NOT NULL DEFAULT 0 CHECK (auto_merge IN (0, 1)),
  demo_videos smallint NOT NULL DEFAULT 1 CHECK (demo_videos IN (0, 1)),
  launchable smallint CHECK (launchable IN (0, 1)),
  auto_resolve_conflicts smallint NOT NULL DEFAULT 0 CHECK (auto_resolve_conflicts IN (0, 1)),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT repositories_installation_provider_fk
    FOREIGN KEY (installation_id, provider)
    REFERENCES app.installations (id, provider) ON DELETE CASCADE,
  CONSTRAINT repositories_id_installation_unique UNIQUE (id, installation_id),
  CONSTRAINT repositories_owner_name_unique UNIQUE (owner, name),
  CONSTRAINT repositories_artifacts_shape CHECK (
    (provider = 'artifacts' AND artifacts_repo IS NOT NULL AND default_branch IS NOT NULL)
    OR (provider = 'github' AND artifacts_repo IS NULL)
  )
);

CREATE INDEX repositories_installation_idx
  ON app.repositories (installation_id, provider, owner, name);
CREATE UNIQUE INDEX repositories_artifacts_repo_unique ON app.repositories (artifacts_repo)
  WHERE artifacts_repo IS NOT NULL;
CREATE INDEX repositories_enabled_idx ON app.repositories (installation_id, id)
  WHERE enabled = 1;

CREATE TABLE app.installation_repo_sync (
  installation_id bigint PRIMARY KEY REFERENCES app.installations (id) ON DELETE CASCADE,
  last_synced_at timestamptz,
  syncing_until timestamptz
);

CREATE TABLE app.repository_refs (
  repository_id bigint NOT NULL REFERENCES app.repositories (id) ON DELETE CASCADE,
  ref text NOT NULL,
  head_sha text NOT NULL,
  pushed_at timestamptz NOT NULL,
  PRIMARY KEY (repository_id, ref)
);

CREATE INDEX repository_refs_head_idx ON app.repository_refs (repository_id, head_sha);

CREATE TABLE app.agents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  installation_id bigint NOT NULL REFERENCES app.installations (id) ON DELETE CASCADE,
  slug text NOT NULL,
  name text NOT NULL,
  description text,
  instructions text NOT NULL,
  model text NOT NULL DEFAULT 'cloudflare/anthropic/claude-sonnet-5',
  is_builtin smallint NOT NULL DEFAULT 0 CHECK (is_builtin IN (0, 1)),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT agents_id_installation_unique UNIQUE (id, installation_id),
  CONSTRAINT agents_installation_slug_unique UNIQUE (installation_id, slug),
  CONSTRAINT agents_slug_format CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

CREATE TABLE app.repo_agents (
  repository_id bigint NOT NULL,
  agent_id bigint NOT NULL,
  installation_id bigint NOT NULL,
  enabled smallint NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  PRIMARY KEY (repository_id, agent_id),
  CONSTRAINT repo_agents_repository_tenant_fk
    FOREIGN KEY (repository_id, installation_id)
    REFERENCES app.repositories (id, installation_id) ON DELETE CASCADE,
  CONSTRAINT repo_agents_agent_tenant_fk
    FOREIGN KEY (agent_id, installation_id)
    REFERENCES app.agents (id, installation_id) ON DELETE CASCADE
);

CREATE INDEX repo_agents_repository_tenant_idx ON app.repo_agents (repository_id, installation_id);
CREATE INDEX repo_agents_agent_tenant_idx ON app.repo_agents (agent_id, installation_id);

CREATE TABLE app.skills (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  installation_id bigint NOT NULL REFERENCES app.installations (id) ON DELETE CASCADE,
  slug text NOT NULL,
  name text NOT NULL,
  description text,
  instructions text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT skills_id_installation_unique UNIQUE (id, installation_id),
  CONSTRAINT skills_installation_slug_unique UNIQUE (installation_id, slug),
  CONSTRAINT skills_slug_format CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

CREATE TABLE app.repo_skills (
  repository_id bigint NOT NULL,
  skill_id bigint NOT NULL,
  installation_id bigint NOT NULL,
  enabled smallint NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  PRIMARY KEY (repository_id, skill_id),
  CONSTRAINT repo_skills_repository_tenant_fk
    FOREIGN KEY (repository_id, installation_id)
    REFERENCES app.repositories (id, installation_id) ON DELETE CASCADE,
  CONSTRAINT repo_skills_skill_tenant_fk
    FOREIGN KEY (skill_id, installation_id)
    REFERENCES app.skills (id, installation_id) ON DELETE CASCADE
);

CREATE INDEX repo_skills_repository_tenant_idx ON app.repo_skills (repository_id, installation_id);
CREATE INDEX repo_skills_skill_tenant_idx ON app.repo_skills (skill_id, installation_id);

CREATE TABLE app.connections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  installation_id bigint NOT NULL REFERENCES app.installations (id) ON DELETE CASCADE,
  name text NOT NULL,
  kind text NOT NULL DEFAULT 'mcp' CHECK (kind IN ('mcp', 'api')),
  url text NOT NULL,
  tool_allowlist jsonb,
  auth_ciphertext text,
  optional smallint NOT NULL DEFAULT 1 CHECK (optional IN (0, 1)),
  auth_type text NOT NULL DEFAULT 'none'
    CHECK (auth_type IN ('none', 'bearer', 'api_key', 'client_credentials', 'oauth')),
  auth_config_ciphertext text,
  oauth_token_expires_at timestamptz,
  oauth_needs_reauth smallint NOT NULL DEFAULT 0 CHECK (oauth_needs_reauth IN (0, 1)),
  oauth_has_refresh_token smallint NOT NULL DEFAULT 0 CHECK (oauth_has_refresh_token IN (0, 1)),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT connections_id_installation_unique UNIQUE (id, installation_id),
  CONSTRAINT connections_installation_name_unique UNIQUE (installation_id, name)
);

CREATE TABLE app.repo_connections (
  repository_id bigint NOT NULL,
  connection_id bigint NOT NULL,
  installation_id bigint NOT NULL,
  reviews smallint NOT NULL DEFAULT 1 CHECK (reviews IN (0, 1)),
  automations smallint NOT NULL DEFAULT 1 CHECK (automations IN (0, 1)),
  PRIMARY KEY (repository_id, connection_id),
  CONSTRAINT repo_connections_repository_tenant_fk
    FOREIGN KEY (repository_id, installation_id)
    REFERENCES app.repositories (id, installation_id) ON DELETE CASCADE,
  CONSTRAINT repo_connections_connection_tenant_fk
    FOREIGN KEY (connection_id, installation_id)
    REFERENCES app.connections (id, installation_id) ON DELETE CASCADE
);

CREATE INDEX repo_connections_repository_tenant_idx
  ON app.repo_connections (repository_id, installation_id);
CREATE INDEX repo_connections_connection_tenant_idx
  ON app.repo_connections (connection_id, installation_id);
