CREATE TABLE "app"."changes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."changes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"repository_id" bigint NOT NULL,
	"provider_key" text NOT NULL,
	"number" integer NOT NULL,
	"origin" text NOT NULL,
	"title" text NOT NULL,
	"external_url" text,
	"source_branch" text NOT NULL,
	"target_branch" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"source_head" text,
	"target_head" text,
	"draft" boolean DEFAULT false NOT NULL,
	"capabilities" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"provider_updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "changes_repo_provider_key_unique" UNIQUE("repository_id","provider_key"),
	CONSTRAINT "changes_number_check" CHECK (number > 0),
	CONSTRAINT "changes_origin_check" CHECK (origin = ANY (ARRAY['human'::text, 'factory'::text, 'automation'::text, 'imported'::text])),
	CONSTRAINT "changes_status_check" CHECK (status = ANY (ARRAY['open'::text, 'merged'::text, 'closed'::text])),
	CONSTRAINT "changes_capabilities_array_check" CHECK (jsonb_typeof(capabilities) = 'array'::text)
);
--> statement-breakpoint
ALTER TABLE "app"."change_requests" ADD COLUMN "change_id" bigint;--> statement-breakpoint
ALTER TABLE "app"."features" ADD COLUMN "change_id" bigint;--> statement-breakpoint
INSERT INTO app.changes (
	repository_id, provider_key, number, origin, title, source_branch, target_branch,
	status, source_head, target_head, draft, capabilities, created_at, updated_at
)
SELECT
	cr.repository_id,
	'artifacts:' || cr.number,
	cr.number,
	CASE WHEN cr.opened_by = 'factory' THEN 'factory' ELSE 'human' END,
	cr.title,
	cr.source_branch,
	cr.target_branch,
	cr.status,
	cr.source_head,
	cr.target_head,
	FALSE,
	'["read_change","publish_review","write_head","publish_check","merge"]'::jsonb,
	cr.created_at,
	cr.updated_at
FROM app.change_requests cr;--> statement-breakpoint
UPDATE app.change_requests cr
SET change_id = c.id
FROM app.changes c
WHERE c.repository_id = cr.repository_id
	AND c.provider_key = 'artifacts:' || cr.number;--> statement-breakpoint
INSERT INTO app.changes (
	repository_id, provider_key, number, origin, title, external_url,
	source_branch, target_branch, status, draft, capabilities, created_at, updated_at
)
SELECT
	f.repository_id,
	'github:' || f.pr_number,
	f.pr_number,
	'factory',
	f.title,
	'https://github.com/' || r.owner || '/' || r.name || '/pull/' || f.pr_number,
	COALESCE(f.branch, 'refs/pull/' || f.pr_number || '/head'),
	COALESCE(r.default_branch, 'main'),
	CASE
		WHEN f.status = 'merged' THEN 'merged'
		WHEN f.status IN ('pr_closed', 'abandoned') THEN 'closed'
		ELSE 'open'
	END,
	FALSE,
	'["read_change","publish_review","write_head","publish_check","merge"]'::jsonb,
	f.created_at,
	CURRENT_TIMESTAMP
FROM app.features f
JOIN app.repositories r ON r.id = f.repository_id AND r.provider = 'github'
WHERE f.pr_number IS NOT NULL
ON CONFLICT (repository_id, provider_key) DO NOTHING;--> statement-breakpoint
UPDATE app.features f
SET change_id = cr.change_id
FROM app.change_requests cr
WHERE cr.feature_id = f.id;--> statement-breakpoint
UPDATE app.features f
SET change_id = c.id
FROM app.repositories r, app.changes c
WHERE r.id = f.repository_id
	AND r.provider = 'github'
	AND c.repository_id = f.repository_id
	AND c.provider_key = 'github:' || f.pr_number
	AND f.pr_number IS NOT NULL;--> statement-breakpoint
ALTER TABLE "app"."changes" ADD CONSTRAINT "changes_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "app"."repositories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "changes_repo_status_idx" ON "app"."changes" USING btree ("repository_id","status","number" DESC NULLS LAST);--> statement-breakpoint
ALTER TABLE "app"."change_requests" ADD CONSTRAINT "change_requests_change_id_changes_id_fk" FOREIGN KEY ("change_id") REFERENCES "app"."changes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."features" ADD CONSTRAINT "features_change_id_changes_id_fk" FOREIGN KEY ("change_id") REFERENCES "app"."changes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "change_requests_change_unique" ON "app"."change_requests" USING btree ("change_id") WHERE (change_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "features_change_idx" ON "app"."features" USING btree ("change_id") WHERE (change_id IS NOT NULL);
