CREATE TABLE app.todos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  installation_id bigint NOT NULL REFERENCES app.installations (id) ON DELETE CASCADE,
  title text NOT NULL,
  notes text,
  created_by_login text,
  created_by_id bigint,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app.plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id bigint NOT NULL REFERENCES app.repositories (id) ON DELETE CASCADE,
  todo_id bigint REFERENCES app.todos (id) ON DELETE SET NULL,
  title text NOT NULL,
  requirements text NOT NULL,
  analysis text,
  questions jsonb,
  answers jsonb,
  plan text,
  acceptance jsonb,
  status text NOT NULL DEFAULT 'analyzing' CHECK (
    status IN ('analyzing', 'awaiting_answers', 'refining', 'plan_ready', 'approving', 'approved', 'failed')
  ),
  error text,
  created_by_login text,
  created_by_id bigint,
  tier text,
  archived smallint NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),
  feedback text,
  attachments jsonb,
  runner_model text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT plans_todo_unique UNIQUE (todo_id)
);

CREATE INDEX plans_repository_created_idx ON app.plans (repository_id, created_at DESC);
CREATE INDEX plans_active_idx ON app.plans (repository_id, id DESC) WHERE archived = 0;

CREATE TABLE app.features (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id bigint NOT NULL REFERENCES app.repositories (id) ON DELETE CASCADE,
  plan_id bigint REFERENCES app.plans (id) ON DELETE SET NULL,
  title text NOT NULL,
  spec text NOT NULL,
  acceptance jsonb,
  branch text,
  pr_number integer CHECK (pr_number > 0),
  status text NOT NULL DEFAULT 'queued' CHECK (
    status IN ('queued', 'generating', 'pr_opened', 'no_changes', 'checks_failed', 'failed', 'merged', 'pr_closed', 'abandoned')
  ),
  error text,
  author_login text,
  author_id bigint,
  coauthor_login text,
  coauthor_id bigint,
  run_started_at timestamptz,
  tier text,
  input_tokens bigint NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
  output_tokens bigint NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
  cache_read_tokens bigint NOT NULL DEFAULT 0 CHECK (cache_read_tokens >= 0),
  cache_write_tokens bigint NOT NULL DEFAULT 0 CHECK (cache_write_tokens >= 0),
  cost_usd numeric(20, 10) NOT NULL DEFAULT 0 CHECK (cost_usd >= 0),
  model text,
  runner_model text,
  change_request_id bigint,
  criteria_conflict smallint NOT NULL DEFAULT 0 CHECK (criteria_conflict IN (0, 1)),
  acceptance_updated_at timestamptz,
  proposed_acceptance jsonb,
  chat_session_id text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT features_plan_repository_unique UNIQUE (plan_id, repository_id)
);

ALTER TABLE app.plans ADD COLUMN feature_id bigint REFERENCES app.features (id) ON DELETE SET NULL;
ALTER TABLE app.todos ADD COLUMN plan_id bigint REFERENCES app.plans (id) ON DELETE SET NULL;
CREATE INDEX plans_feature_idx ON app.plans (feature_id) WHERE feature_id IS NOT NULL;
CREATE UNIQUE INDEX todos_plan_unique ON app.todos (plan_id) WHERE plan_id IS NOT NULL;

CREATE INDEX todos_installation_unplanned_idx ON app.todos (installation_id, id DESC)
  WHERE plan_id IS NULL;
CREATE INDEX features_repository_created_idx ON app.features (repository_id, id DESC);
CREATE INDEX features_repository_pr_idx ON app.features (repository_id, pr_number, id DESC)
  WHERE pr_number IS NOT NULL;
CREATE INDEX features_plan_idx ON app.features (plan_id) WHERE plan_id IS NOT NULL;
CREATE INDEX features_open_pr_idx ON app.features (repository_id, pr_number)
  WHERE status = 'pr_opened' AND pr_number IS NOT NULL;
CREATE INDEX features_generating_created_idx ON app.features (created_at)
  WHERE status = 'generating';

CREATE TABLE app.todo_repositories (
  todo_id bigint NOT NULL REFERENCES app.todos (id) ON DELETE CASCADE,
  repository_id bigint NOT NULL REFERENCES app.repositories (id) ON DELETE CASCADE,
  position smallint NOT NULL CHECK (position BETWEEN 0 AND 2),
  PRIMARY KEY (todo_id, repository_id),
  CONSTRAINT todo_repositories_position_unique UNIQUE (todo_id, position)
);

CREATE INDEX todo_repositories_repository_idx ON app.todo_repositories (repository_id);

CREATE TABLE app.plan_repositories (
  plan_id bigint NOT NULL REFERENCES app.plans (id) ON DELETE CASCADE,
  repository_id bigint NOT NULL REFERENCES app.repositories (id) ON DELETE CASCADE,
  position smallint NOT NULL CHECK (position BETWEEN 0 AND 2),
  PRIMARY KEY (plan_id, repository_id),
  CONSTRAINT plan_repositories_position_unique UNIQUE (plan_id, position)
);

CREATE INDEX plan_repositories_repository_idx ON app.plan_repositories (repository_id);

CREATE TABLE app.reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id bigint NOT NULL,
  installation_id bigint NOT NULL,
  pr_number integer NOT NULL CHECK (pr_number > 0),
  trigger_event text NOT NULL,
  status text NOT NULL DEFAULT 'completed' CHECK (status IN ('running', 'completed', 'failed')),
  completed_at timestamptz,
  review_url text,
  input_tokens bigint NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
  output_tokens bigint NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
  cache_read_tokens bigint NOT NULL DEFAULT 0 CHECK (cache_read_tokens >= 0),
  cache_write_tokens bigint NOT NULL DEFAULT 0 CHECK (cache_write_tokens >= 0),
  cost_usd numeric(20, 10) NOT NULL DEFAULT 0 CHECK (cost_usd >= 0),
  model text,
  agent_slug text,
  agent_instance_id text,
  risk_tier text CHECK (risk_tier IS NULL OR risk_tier IN ('trivial', 'lite', 'full')),
  findings_count integer CHECK (findings_count IS NULL OR findings_count >= 0),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT reviews_repository_tenant_fk
    FOREIGN KEY (repository_id, installation_id)
    REFERENCES app.repositories (id, installation_id) ON DELETE CASCADE,
  CONSTRAINT reviews_completion_shape CHECK (
    (status = 'running' AND completed_at IS NULL) OR status <> 'running'
  )
);

CREATE INDEX reviews_installation_time_idx ON app.reviews (installation_id, created_at DESC);
CREATE INDEX reviews_repository_installation_idx ON app.reviews (repository_id, installation_id);
CREATE INDEX reviews_repo_pr_idx ON app.reviews (repository_id, pr_number, id DESC);
CREATE INDEX reviews_agent_instance_idx ON app.reviews (agent_instance_id);
CREATE UNIQUE INDEX reviews_one_running_instance_idx ON app.reviews (agent_instance_id)
  WHERE status = 'running' AND agent_instance_id IS NOT NULL;
CREATE INDEX reviews_running_installation_idx ON app.reviews (installation_id, created_at)
  WHERE status = 'running';

CREATE TABLE app.fix_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id bigint NOT NULL REFERENCES app.repositories (id) ON DELETE CASCADE,
  pr_number integer NOT NULL CHECK (pr_number > 0),
  "trigger" text NOT NULL,
  status text NOT NULL DEFAULT 'running' CHECK (
    status IN ('running', 'fixed', 'no_changes', 'tests_failed', 'failed')
  ),
  commit_sha text,
  error text,
  input_tokens bigint NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
  output_tokens bigint NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
  cache_read_tokens bigint NOT NULL DEFAULT 0 CHECK (cache_read_tokens >= 0),
  cache_write_tokens bigint NOT NULL DEFAULT 0 CHECK (cache_write_tokens >= 0),
  cost_usd numeric(20, 10) NOT NULL DEFAULT 0 CHECK (cost_usd >= 0),
  model text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX fix_attempts_pr_idx ON app.fix_attempts (repository_id, pr_number, id DESC);
CREATE UNIQUE INDEX fix_attempts_one_running_idx ON app.fix_attempts (repository_id, pr_number)
  WHERE status = 'running';

CREATE TABLE app.verifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_id bigint NOT NULL REFERENCES app.features (id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'running' CHECK (
    status IN ('running', 'passed', 'failed', 'error', 'skipped')
  ),
  results jsonb,
  summary text,
  error text,
  demo jsonb,
  input_tokens bigint NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
  output_tokens bigint NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
  cache_read_tokens bigint NOT NULL DEFAULT 0 CHECK (cache_read_tokens >= 0),
  cache_write_tokens bigint NOT NULL DEFAULT 0 CHECK (cache_write_tokens >= 0),
  cost_usd numeric(20, 10) NOT NULL DEFAULT 0 CHECK (cost_usd >= 0),
  model text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX verifications_feature_idx ON app.verifications (feature_id, id DESC);
CREATE UNIQUE INDEX verifications_one_running_idx ON app.verifications (feature_id)
  WHERE status = 'running';
CREATE INDEX verifications_running_created_idx ON app.verifications (created_at)
  WHERE status = 'running';

CREATE TABLE app.cockpit_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_id bigint NOT NULL REFERENCES app.features (id) ON DELETE CASCADE,
  path text NOT NULL,
  line integer NOT NULL CHECK (line > 0),
  side text NOT NULL DEFAULT 'additions' CHECK (side IN ('additions', 'deletions')),
  body text NOT NULL,
  author text NOT NULL,
  author_id bigint,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'dispatched')),
  fix_attempt_id bigint REFERENCES app.fix_attempts (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX cockpit_comments_feature_idx ON app.cockpit_comments (feature_id, id);
CREATE INDEX cockpit_comments_fix_attempt_idx ON app.cockpit_comments (fix_attempt_id)
  WHERE fix_attempt_id IS NOT NULL;

CREATE TABLE app.chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_id bigint NOT NULL REFERENCES app.features (id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('user', 'assistant')),
  body text NOT NULL,
  author text,
  author_id bigint,
  status text NOT NULL DEFAULT 'done' CHECK (status IN ('queued', 'running', 'done', 'failed')),
  outcome text CHECK (outcome IS NULL OR outcome IN ('changed', 'no_changes', 'tests_failed')),
  commit_sha text,
  error text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX chat_messages_feature_idx ON app.chat_messages (feature_id, id);
CREATE UNIQUE INDEX chat_messages_one_pending_user_idx ON app.chat_messages (feature_id)
  WHERE role = 'user' AND status IN ('queued', 'running');

CREATE TABLE app.automations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id bigint NOT NULL REFERENCES app.repositories (id) ON DELETE CASCADE,
  name text NOT NULL,
  prompt text NOT NULL,
  schedule_kind text NOT NULL CHECK (schedule_kind IN ('hourly', 'daily', 'weekly')),
  time_of_day time,
  day_of_week smallint CHECK (day_of_week BETWEEN 0 AND 6),
  enabled smallint NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  next_run_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT automations_schedule_shape CHECK (
    (schedule_kind = 'hourly' AND time_of_day IS NULL AND day_of_week IS NULL)
    OR (schedule_kind = 'daily' AND time_of_day IS NOT NULL AND day_of_week IS NULL)
    OR (schedule_kind = 'weekly' AND time_of_day IS NOT NULL AND day_of_week IS NOT NULL)
  )
);

CREATE INDEX automations_repository_idx ON app.automations (repository_id, id);
CREATE INDEX automations_due_idx ON app.automations (next_run_at) WHERE enabled = 1;

CREATE TABLE app.automation_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  automation_id bigint NOT NULL REFERENCES app.automations (id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'running' CHECK (
    status IN ('running', 'pr_opened', 'no_changes', 'checks_failed', 'failed')
  ),
  pr_number integer CHECK (pr_number IS NULL OR pr_number > 0),
  commit_sha text,
  error text,
  input_tokens bigint NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
  output_tokens bigint NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
  cache_read_tokens bigint NOT NULL DEFAULT 0 CHECK (cache_read_tokens >= 0),
  cache_write_tokens bigint NOT NULL DEFAULT 0 CHECK (cache_write_tokens >= 0),
  cost_usd numeric(20, 10) NOT NULL DEFAULT 0 CHECK (cost_usd >= 0),
  model text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX automation_runs_automation_idx ON app.automation_runs (automation_id, created_at DESC);
CREATE UNIQUE INDEX automation_runs_one_running_idx ON app.automation_runs (automation_id)
  WHERE status = 'running';

CREATE TABLE app.agent_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL CHECK (
    kind IN ('plan_analyze', 'plan_refine', 'generate', 'verify', 'fix', 'automation', 'chat', 'resolve_conflict')
  ),
  plan_id bigint REFERENCES app.plans (id) ON DELETE CASCADE,
  feature_id bigint REFERENCES app.features (id) ON DELETE CASCADE,
  fix_attempt_id bigint REFERENCES app.fix_attempts (id) ON DELETE CASCADE,
  automation_run_id bigint REFERENCES app.automation_runs (id) ON DELETE CASCADE,
  log_key text NOT NULL,
  success smallint NOT NULL CHECK (success IN (0, 1)),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT agent_runs_owner CHECK (
    num_nonnulls(plan_id, feature_id, fix_attempt_id, automation_run_id) >= 1
  )
);

CREATE INDEX agent_runs_plan_idx ON app.agent_runs (plan_id) WHERE plan_id IS NOT NULL;
CREATE INDEX agent_runs_feature_idx ON app.agent_runs (feature_id) WHERE feature_id IS NOT NULL;
CREATE INDEX agent_runs_fix_attempt_idx ON app.agent_runs (fix_attempt_id) WHERE fix_attempt_id IS NOT NULL;
CREATE INDEX agent_runs_automation_idx ON app.agent_runs (automation_run_id)
  WHERE automation_run_id IS NOT NULL;
