CREATE TABLE auth."organization" (
  "id" text PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "logo" text,
  "metadata" text,
  "createdAt" timestamptz NOT NULL,
  "installationId" bigint NOT NULL UNIQUE REFERENCES app.installations (id) ON DELETE CASCADE
);

ALTER TABLE auth."session"
  ADD CONSTRAINT session_active_organization_fk
  FOREIGN KEY ("activeOrganizationId") REFERENCES auth."organization" ("id") ON DELETE SET NULL;

CREATE TABLE auth."member" (
  "id" text PRIMARY KEY,
  "organizationId" text NOT NULL REFERENCES auth."organization" ("id") ON DELETE CASCADE,
  "userId" text NOT NULL REFERENCES auth."user" ("id") ON DELETE CASCADE,
  "role" text NOT NULL DEFAULT 'member' CHECK ("role" IN ('owner', 'admin', 'member')),
  "createdAt" timestamptz NOT NULL,
  CONSTRAINT member_organization_user_unique UNIQUE ("organizationId", "userId")
);

CREATE INDEX member_user_id_idx ON auth."member" ("userId");

CREATE TABLE auth."invitation" (
  "id" text PRIMARY KEY,
  "organizationId" text NOT NULL REFERENCES auth."organization" ("id") ON DELETE CASCADE,
  "email" text NOT NULL,
  "role" text NOT NULL CHECK ("role" IN ('owner', 'admin', 'member')),
  "status" text NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending', 'accepted', 'rejected', 'canceled')),
  "expiresAt" timestamptz NOT NULL,
  "createdAt" timestamptz NOT NULL,
  "inviterId" text NOT NULL REFERENCES auth."user" ("id") ON DELETE CASCADE
);

CREATE INDEX invitation_organization_idx ON auth."invitation" ("organizationId", "status");
CREATE INDEX invitation_inviter_idx ON auth."invitation" ("inviterId");
CREATE INDEX invitation_email_status_idx ON auth."invitation" ("email", "status");
CREATE UNIQUE INDEX invitation_pending_email_unique
  ON auth."invitation" ("organizationId", lower("email")) WHERE "status" = 'pending';

CREATE TABLE app.user_tokens (
  user_id bigint PRIMARY KEY,
  login text NOT NULL,
  refresh_ciphertext text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app.user_installation_access (
  user_id text PRIMARY KEY REFERENCES auth."user" ("id") ON DELETE CASCADE,
  installation_ids bigint[] NOT NULL DEFAULT '{}',
  verified_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_installation_access_no_null_ids
    CHECK (array_position(installation_ids, NULL) IS NULL)
);

CREATE TABLE app.push_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_github_id bigint NOT NULL REFERENCES auth."user" ("githubId") ON DELETE CASCADE,
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX push_subscriptions_user_idx ON app.push_subscriptions (user_github_id);

CREATE TABLE app.change_request_counters (
  repository_id bigint PRIMARY KEY REFERENCES app.repositories (id) ON DELETE CASCADE,
  last_number integer NOT NULL CHECK (last_number > 0)
);

CREATE FUNCTION app.next_change_request_number(target_repository_id bigint)
RETURNS integer
LANGUAGE sql
AS $function$
  INSERT INTO app.change_request_counters (repository_id, last_number)
  VALUES (target_repository_id, 1)
  ON CONFLICT (repository_id)
  DO UPDATE SET last_number = app.change_request_counters.last_number + 1
  RETURNING last_number
$function$;

CREATE TABLE app.change_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id bigint NOT NULL REFERENCES app.repositories (id) ON DELETE CASCADE,
  number integer NOT NULL CHECK (number > 0),
  feature_id bigint REFERENCES app.features (id) ON DELETE SET NULL,
  title text NOT NULL,
  source_branch text NOT NULL,
  target_branch text NOT NULL,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'merged', 'closed')),
  source_head text,
  target_head text,
  merge_base text,
  mergeable smallint CHECK (mergeable IN (0, 1)),
  conflict_files jsonb,
  files jsonb,
  diff_key text,
  patch_truncated smallint NOT NULL DEFAULT 0 CHECK (patch_truncated IN (0, 1)),
  review_status text CHECK (review_status IS NULL OR review_status IN ('approved', 'changes_requested')),
  merged_head text,
  opened_by text NOT NULL DEFAULT 'factory',
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT change_requests_repo_number_unique UNIQUE (repository_id, number)
);

CREATE INDEX change_requests_repo_status_idx ON app.change_requests (repository_id, status, number DESC);
CREATE INDEX change_requests_feature_idx ON app.change_requests (feature_id) WHERE feature_id IS NOT NULL;
CREATE UNIQUE INDEX change_requests_open_branches_unique
  ON app.change_requests (repository_id, source_branch, target_branch) WHERE status = 'open';

ALTER TABLE app.features
  ADD CONSTRAINT features_change_request_fk
  FOREIGN KEY (change_request_id) REFERENCES app.change_requests (id) ON DELETE SET NULL;

CREATE INDEX features_change_request_idx ON app.features (change_request_id)
  WHERE change_request_id IS NOT NULL;

CREATE TABLE app.cr_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  change_request_id bigint NOT NULL REFERENCES app.change_requests (id) ON DELETE CASCADE,
  file text,
  line integer CHECK (line IS NULL OR line > 0),
  author text NOT NULL,
  kind text NOT NULL DEFAULT 'comment' CHECK (kind IN ('comment', 'finding', 'summary')),
  severity text CHECK (severity IS NULL OR severity IN ('P1', 'P2', 'P3')),
  body text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT cr_comments_location CHECK ((file IS NULL AND line IS NULL) OR file IS NOT NULL)
);

CREATE INDEX cr_comments_change_request_idx ON app.cr_comments (change_request_id, id);

CREATE TABLE app.cr_checks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  change_request_id bigint NOT NULL REFERENCES app.change_requests (id) ON DELETE CASCADE,
  name text NOT NULL,
  status text NOT NULL CHECK (status IN ('running', 'passed', 'failed', 'error')),
  summary text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT cr_checks_name_unique UNIQUE (change_request_id, name)
);
