CREATE TABLE "app"."acceptance_contracts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."acceptance_contracts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"work_item_id" bigint,
	"change_id" bigint,
	"version" integer NOT NULL,
	"criteria" jsonb NOT NULL,
	"source" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "acceptance_contracts_version_check" CHECK (version > 0),
	CONSTRAINT "acceptance_contracts_owner_check" CHECK ((work_item_id IS NOT NULL) OR (change_id IS NOT NULL)),
	CONSTRAINT "acceptance_contracts_criteria_array_check" CHECK (jsonb_typeof(criteria) = 'array'::text)
);
--> statement-breakpoint
CREATE TABLE "app"."factory_runs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."factory_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"repository_id" bigint NOT NULL,
	"work_item_id" bigint,
	"change_id" bigint,
	"profile_key" text NOT NULL,
	"start_stage" text NOT NULL,
	"stop_after_stage" text NOT NULL,
	"policy_snapshot" jsonb NOT NULL,
	"trigger" text NOT NULL,
	"actor" text,
	"status" text DEFAULT 'active' NOT NULL,
	"handoff_reason" text,
	"idempotency_key" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"completed_at" timestamp with time zone,
	CONSTRAINT "factory_runs_idempotency_key_unique" UNIQUE("idempotency_key"),
	CONSTRAINT "factory_runs_status_check" CHECK (status = ANY (ARRAY['active'::text, 'awaiting_human'::text, 'handed_off'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
	CONSTRAINT "factory_runs_profile_check" CHECK (profile_key = ANY (ARRAY['review_on_demand'::text, 'automatic_review'::text, 'review_and_repair'::text, 'idea_to_pr'::text, 'assisted_delivery'::text, 'full_delivery'::text, 'native_turnkey'::text, 'legacy_factory'::text])),
	CONSTRAINT "factory_runs_stage_check" CHECK (start_stage = ANY (ARRAY['plan'::text, 'implement'::text, 'publish'::text, 'review'::text, 'repair'::text, 'verify'::text, 'merge'::text]) AND stop_after_stage = ANY (ARRAY['plan'::text, 'implement'::text, 'publish'::text, 'review'::text, 'repair'::text, 'verify'::text, 'merge'::text])),
	CONSTRAINT "factory_runs_stage_order_check" CHECK (array_position(ARRAY['plan'::text, 'implement'::text, 'publish'::text, 'review'::text, 'repair'::text, 'verify'::text, 'merge'::text], start_stage) <= array_position(ARRAY['plan'::text, 'implement'::text, 'publish'::text, 'review'::text, 'repair'::text, 'verify'::text, 'merge'::text], stop_after_stage)),
	CONSTRAINT "factory_runs_policy_object_check" CHECK (jsonb_typeof(policy_snapshot) = 'object'::text)
);
--> statement-breakpoint
CREATE TABLE "app"."lifecycle_events" (
	"idempotency_key" text PRIMARY KEY NOT NULL,
	"factory_run_id" bigint,
	"change_id" bigint,
	"kind" text NOT NULL,
	"payload" jsonb,
	"decision" jsonb,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "lifecycle_events_kind_check" CHECK (kind = ANY (ARRAY['work.requested'::text, 'plan.ready'::text, 'human.approved'::text, 'change.opened'::text, 'change.updated'::text, 'change.closed'::text, 'stage.completed'::text, 'stage.failed'::text, 'external.checks_updated'::text, 'human.resume_requested'::text, 'human.handoff_requested'::text, 'run.cancelled'::text]))
);
--> statement-breakpoint
CREATE TABLE "app"."stage_runs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."stage_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"factory_run_id" bigint NOT NULL,
	"change_id" bigint,
	"stage" text NOT NULL,
	"attempt" integer DEFAULT 1 NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"trigger" text NOT NULL,
	"input" jsonb,
	"output" jsonb,
	"workflow_instance" text,
	"error" text,
	"idempotency_key" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	CONSTRAINT "stage_runs_idempotency_key_unique" UNIQUE("idempotency_key"),
	CONSTRAINT "stage_runs_attempt_unique" UNIQUE("factory_run_id","stage","attempt"),
	CONSTRAINT "stage_runs_attempt_check" CHECK (attempt > 0),
	CONSTRAINT "stage_runs_status_check" CHECK (status = ANY (ARRAY['queued'::text, 'running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
	CONSTRAINT "stage_runs_stage_check" CHECK (stage = ANY (ARRAY['plan'::text, 'implement'::text, 'publish'::text, 'review'::text, 'repair'::text, 'verify'::text, 'merge'::text]))
);
--> statement-breakpoint
CREATE TABLE "app"."work_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."work_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"repository_id" bigint,
	"origin" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "work_items_origin_check" CHECK (origin = ANY (ARRAY['idea'::text, 'issue'::text, 'external_change'::text, 'automation'::text, 'api'::text])),
	CONSTRAINT "work_items_status_check" CHECK (status = ANY (ARRAY['open'::text, 'closed'::text]))
);
--> statement-breakpoint
ALTER TABLE "app"."repositories" ADD COLUMN "process_profile" text DEFAULT 'legacy_factory' NOT NULL;--> statement-breakpoint
UPDATE app.repositories
SET process_profile = CASE review_intake
	WHEN 'on_demand' THEN 'review_on_demand'
	WHEN 'all_changes' THEN 'automatic_review'
	ELSE 'legacy_factory'
END;--> statement-breakpoint
ALTER TABLE "app"."acceptance_contracts" ADD CONSTRAINT "acceptance_contracts_work_item_id_fkey" FOREIGN KEY ("work_item_id") REFERENCES "app"."work_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."acceptance_contracts" ADD CONSTRAINT "acceptance_contracts_change_id_fkey" FOREIGN KEY ("change_id") REFERENCES "app"."changes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."factory_runs" ADD CONSTRAINT "factory_runs_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "app"."repositories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."factory_runs" ADD CONSTRAINT "factory_runs_work_item_id_fkey" FOREIGN KEY ("work_item_id") REFERENCES "app"."work_items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."factory_runs" ADD CONSTRAINT "factory_runs_change_id_fkey" FOREIGN KEY ("change_id") REFERENCES "app"."changes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."lifecycle_events" ADD CONSTRAINT "lifecycle_events_factory_run_id_fkey" FOREIGN KEY ("factory_run_id") REFERENCES "app"."factory_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."lifecycle_events" ADD CONSTRAINT "lifecycle_events_change_id_fkey" FOREIGN KEY ("change_id") REFERENCES "app"."changes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."stage_runs" ADD CONSTRAINT "stage_runs_factory_run_id_fkey" FOREIGN KEY ("factory_run_id") REFERENCES "app"."factory_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."stage_runs" ADD CONSTRAINT "stage_runs_change_id_fkey" FOREIGN KEY ("change_id") REFERENCES "app"."changes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."work_items" ADD CONSTRAINT "work_items_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "app"."repositories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "acceptance_contracts_work_item_idx" ON "app"."acceptance_contracts" USING btree ("work_item_id","version" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "acceptance_contracts_change_idx" ON "app"."acceptance_contracts" USING btree ("change_id","version" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "factory_runs_repo_created_idx" ON "app"."factory_runs" USING btree ("repository_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "factory_runs_change_idx" ON "app"."factory_runs" USING btree ("change_id","created_at" DESC NULLS LAST) WHERE (change_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "factory_runs_work_item_idx" ON "app"."factory_runs" USING btree ("work_item_id","created_at" DESC NULLS LAST) WHERE (work_item_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "lifecycle_events_factory_run_idx" ON "app"."lifecycle_events" USING btree ("factory_run_id","created_at");--> statement-breakpoint
CREATE INDEX "lifecycle_events_change_idx" ON "app"."lifecycle_events" USING btree ("change_id","created_at") WHERE (change_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "stage_runs_factory_run_idx" ON "app"."stage_runs" USING btree ("factory_run_id","id");--> statement-breakpoint
CREATE INDEX "stage_runs_change_idx" ON "app"."stage_runs" USING btree ("change_id","id" DESC NULLS LAST) WHERE (change_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "work_items_repo_created_idx" ON "app"."work_items" USING btree ("repository_id","created_at" DESC NULLS LAST);--> statement-breakpoint
ALTER TABLE "app"."repositories" ADD CONSTRAINT "repositories_process_profile_check" CHECK (process_profile = ANY (ARRAY['review_on_demand'::text, 'automatic_review'::text, 'review_and_repair'::text, 'idea_to_pr'::text, 'assisted_delivery'::text, 'full_delivery'::text, 'native_turnkey'::text, 'legacy_factory'::text]));
