CREATE TABLE "app"."models" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."models_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"model_id" text NOT NULL,
	"provider" text DEFAULT 'anthropic' NOT NULL,
	"label" text NOT NULL,
	"for_runner" boolean DEFAULT true NOT NULL,
	"for_reviewer" boolean DEFAULT true NOT NULL,
	"runner_default" boolean DEFAULT false NOT NULL,
	"reviewer_default" boolean DEFAULT false NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "models_provider_model_unique" UNIQUE("provider","model_id")
);
--> statement-breakpoint
CREATE UNIQUE INDEX "models_runner_default_unique" ON "app"."models" USING btree ("runner_default") WHERE runner_default;--> statement-breakpoint
CREATE UNIQUE INDEX "models_reviewer_default_unique" ON "app"."models" USING btree ("reviewer_default") WHERE reviewer_default;--> statement-breakpoint
INSERT INTO "app"."models"
  ("model_id", "provider", "label", "for_runner", "for_reviewer", "runner_default", "reviewer_default", "sort_order")
VALUES
  ('claude-fable-5', 'anthropic', 'Fable 5', true, true, true, false, 0),
  ('claude-opus-5', 'anthropic', 'Opus 5', true, true, false, false, 1),
  ('claude-sonnet-5', 'anthropic', 'Sonnet 5', true, true, false, true, 2),
  ('claude-haiku-4-5-20251001', 'anthropic', 'Haiku 4.5', true, true, false, false, 3);