CREATE TABLE "app"."feature_explanations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."feature_explanations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"feature_id" bigint NOT NULL,
	"head_sha" text NOT NULL,
	"status" text DEFAULT 'running' NOT NULL,
	"agent_instance_id" text NOT NULL,
	"document" jsonb,
	"model" text,
	"error" text,
	"input_tokens" bigint DEFAULT 0 NOT NULL,
	"output_tokens" bigint DEFAULT 0 NOT NULL,
	"cache_read_tokens" bigint DEFAULT 0 NOT NULL,
	"cache_write_tokens" bigint DEFAULT 0 NOT NULL,
	"cost_usd" numeric(20, 10) DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"completed_at" timestamp with time zone,
	CONSTRAINT "feature_explanations_status_check" CHECK (status = ANY (ARRAY['running'::text, 'ready'::text, 'failed'::text]))
);
--> statement-breakpoint
ALTER TABLE "app"."feature_explanations" ADD CONSTRAINT "feature_explanations_feature_id_fkey" FOREIGN KEY ("feature_id") REFERENCES "app"."features"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "feature_explanations_feature_head_idx" ON "app"."feature_explanations" USING btree ("feature_id","head_sha","id" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "feature_explanations_instance_idx" ON "app"."feature_explanations" USING btree ("agent_instance_id");--> statement-breakpoint
CREATE UNIQUE INDEX "feature_explanations_one_running_idx" ON "app"."feature_explanations" USING btree ("feature_id") WHERE (status = 'running'::text);