CREATE TABLE "app"."review_findings" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."review_findings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"review_id" bigint NOT NULL,
	"candidate_index" integer NOT NULL,
	"path" text NOT NULL,
	"line" integer NOT NULL,
	"side" text NOT NULL,
	"severity" text NOT NULL,
	"body" text NOT NULL,
	"evidence" text NOT NULL,
	"failure_path" text NOT NULL,
	"published" boolean DEFAULT false NOT NULL,
	"verifier_confidence" text,
	"verifier_severity" text,
	"verification_reason" text,
	"feedback" text,
	"feedback_by_github_id" bigint,
	"feedback_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "review_findings_review_candidate_unique" UNIQUE("review_id","candidate_index"),
	CONSTRAINT "review_findings_candidate_index_check" CHECK (candidate_index >= 0),
	CONSTRAINT "review_findings_line_check" CHECK (line > 0),
	CONSTRAINT "review_findings_side_check" CHECK (side = ANY (ARRAY['LEFT'::text, 'RIGHT'::text])),
	CONSTRAINT "review_findings_severity_check" CHECK (severity = ANY (ARRAY['P1'::text, 'P2'::text])),
	CONSTRAINT "review_findings_verifier_confidence_check" CHECK ((verifier_confidence IS NULL) OR (verifier_confidence = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text]))),
	CONSTRAINT "review_findings_verifier_severity_check" CHECK ((verifier_severity IS NULL) OR (verifier_severity = ANY (ARRAY['P1'::text, 'P2'::text]))),
	CONSTRAINT "review_findings_feedback_check" CHECK ((feedback IS NULL) OR (feedback = ANY (ARRAY['useful'::text, 'false_positive'::text, 'fixed'::text, 'dismissed'::text])))
);
--> statement-breakpoint
ALTER TABLE "app"."models" ADD COLUMN "reviewer_experiment_weight" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "app"."models" ADD COLUMN "verifier_experiment_weight" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD COLUMN "candidate_count" integer;--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD COLUMN "verification_status" text;--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD COLUMN "verification_model" text;--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD COLUMN "verification_input_tokens" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD COLUMN "verification_output_tokens" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD COLUMN "verification_cost_usd" numeric(20, 10) DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD COLUMN "verification_latency_ms" integer;--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD COLUMN "experiment_key" text;--> statement-breakpoint
ALTER TABLE "app"."review_findings" ADD CONSTRAINT "review_findings_review_id_reviews_id_fk" FOREIGN KEY ("review_id") REFERENCES "app"."reviews"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "review_findings_review_idx" ON "app"."review_findings" USING btree ("review_id");--> statement-breakpoint
CREATE INDEX "review_findings_feedback_idx" ON "app"."review_findings" USING btree ("feedback","id" DESC NULLS LAST) WHERE published;--> statement-breakpoint
ALTER TABLE "app"."models" ADD CONSTRAINT "models_reviewer_experiment_weight_check" CHECK (reviewer_experiment_weight >= 0 AND reviewer_experiment_weight <= 10000);--> statement-breakpoint
ALTER TABLE "app"."models" ADD CONSTRAINT "models_verifier_experiment_weight_check" CHECK (verifier_experiment_weight >= 0 AND verifier_experiment_weight <= 10000);--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD CONSTRAINT "reviews_candidate_count_check" CHECK ((candidate_count IS NULL) OR (candidate_count >= 0));--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD CONSTRAINT "reviews_verification_status_check" CHECK ((verification_status IS NULL) OR (verification_status = ANY (ARRAY['skipped'::text, 'completed'::text, 'failed'::text, 'incomplete'::text])));--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD CONSTRAINT "reviews_verification_input_tokens_check" CHECK (verification_input_tokens >= 0);--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD CONSTRAINT "reviews_verification_output_tokens_check" CHECK (verification_output_tokens >= 0);--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD CONSTRAINT "reviews_verification_cost_usd_check" CHECK (verification_cost_usd >= (0)::numeric);--> statement-breakpoint
ALTER TABLE "app"."reviews" ADD CONSTRAINT "reviews_verification_latency_ms_check" CHECK ((verification_latency_ms IS NULL) OR (verification_latency_ms >= 0));