CREATE TABLE "app"."review_file_evidence" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."review_file_evidence_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"review_id" bigint NOT NULL,
	"path" text NOT NULL,
	"patch_delivered" boolean DEFAULT false NOT NULL,
	"disposition" text,
	"evidence" text,
	"delivered_at" timestamp with time zone,
	"acknowledged_at" timestamp with time zone,
	CONSTRAINT "review_file_evidence_review_path_unique" UNIQUE("review_id","path"),
	CONSTRAINT "review_file_evidence_disposition_check" CHECK ((disposition IS NULL) OR (disposition = ANY (ARRAY['reviewed'::text, 'blocked'::text]))),
	CONSTRAINT "review_file_evidence_ack_shape_check" CHECK ((disposition IS NULL AND evidence IS NULL AND acknowledged_at IS NULL) OR
        (disposition IS NOT NULL AND evidence IS NOT NULL AND acknowledged_at IS NOT NULL))
);
--> statement-breakpoint
ALTER TABLE "app"."review_file_evidence" ADD CONSTRAINT "review_file_evidence_review_id_reviews_id_fk" FOREIGN KEY ("review_id") REFERENCES "app"."reviews"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "review_file_evidence_review_idx" ON "app"."review_file_evidence" USING btree ("review_id");