CREATE TABLE "app"."review_patch_deliveries" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."review_patch_deliveries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 START WITH 1 CACHE 1),
	"review_id" bigint NOT NULL,
	"path" text NOT NULL,
	"chunk_index" integer NOT NULL,
	"chunk_count" integer NOT NULL,
	"delivered_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "review_patch_deliveries_review_path_chunk_unique" UNIQUE("review_id","path","chunk_index"),
	CONSTRAINT "review_patch_deliveries_chunk_index_check" CHECK (chunk_index >= 0),
	CONSTRAINT "review_patch_deliveries_chunk_count_check" CHECK (chunk_count > 0),
	CONSTRAINT "review_patch_deliveries_chunk_range_check" CHECK (chunk_index < chunk_count)
);
--> statement-breakpoint
ALTER TABLE "app"."models" ADD COLUMN "review_diff_tokens" integer DEFAULT 64000 NOT NULL;--> statement-breakpoint
ALTER TABLE "app"."review_patch_deliveries" ADD CONSTRAINT "review_patch_deliveries_review_id_reviews_id_fk" FOREIGN KEY ("review_id") REFERENCES "app"."reviews"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "review_patch_deliveries_review_idx" ON "app"."review_patch_deliveries" USING btree ("review_id","path");--> statement-breakpoint
ALTER TABLE "app"."models" ADD CONSTRAINT "models_review_diff_tokens_check" CHECK (review_diff_tokens >= 8000 AND review_diff_tokens <= 200000);