allowBuilds:
  '@google/genai': false
  '@mongodb-js/zstd': false
  core-js-pure: false
  esbuild: true
  node-liblzma: false
  protobufjs: false
  workerd: true
patchedDependencies:
  '@flue/runtime': patches/@flue__runtime.patch
